In [1]:
from pathlib import Path
import duckdb
from sklearn.model_selection import StratifiedKFold
import pandas as pd
from itertools import product
import os
import sys
sys.path.append(str(Path(os.getcwd()).parent.absolute()))

from ringer_zero.utils import walk_paths

import colorlog
logger = colorlog.getLogger()

In [2]:
BASE_QEUERY = """
SELECT 
    id,
    target,
    el_lhmedium,
    el_lhvloose,
    IF({et_col} < 0, 0, {et_col}) AS {et_col}_normalized,
    ABS({eta_col}) AS {eta_col}_normalized,
    CASE WHEN el_lhmedium AND target=1 THEN TRUE
         WHEN NOT el_lhvloose AND target=0 THEN FALSE
         ELSE NULL END AS standard_binning_label,
FROM read_parquet('{table_data_path}')
WHERE {et_col}_normalized >= {et_bin_left} AND
      {et_col}_normalized < {et_bin_right} AND
      {eta_col}_normalized >= {eta_bin_left} AND
      {eta_col}_normalized < {eta_bin_right} AND
      standard_binning_label IS NOT NULL;
"""

RESULT_QUERY = """
SELECT
    id,
    CASE WHEN el_lhmedium AND target=1 THEN TRUE
         WHEN NOT el_lhvloose AND target=0 THEN FALSE
         ELSE NULL END AS standard_binning_label,
    NULL AS standard_binning_kfold
FROM read_parquet('{table_data_path}');
"""

In [ ]:
dataset_dir = Path('/media/lucasbanunes/KINGSTON/data/cern-datasets/mc21_isabela_qt_no_restriction')
et_bins = [15, 20, 30, 40, 50, int(1e12)]
et_col = 'trig_L2_calo_et'
eta_bins = [0, 0.8, 1.37, 1.52, 2.500001]
eta_col = 'trig_L2_calo_eta'
splitter = StratifiedKFold(n_splits=5, shuffle=True)

In [4]:
result_query = RESULT_QUERY.format(
    table_data_path=str(dataset_dir / 'data.parquet' / 'data_*.parquet')
)
results_df = duckdb.query(result_query).fetch_arrow_table().to_pandas(types_mapper=pd.ArrowDtype)
results_df

              id standard_binning_label  standard_binning_kfold
0              0                  False                    <NA>
1              1                  False                    <NA>
2              2                  False                    <NA>
3              3                  False                    <NA>
4              4                  False                    <NA>
...          ...                    ...                     ...
7247094  7247094                   True                    <NA>
7247095  7247095                   True                    <NA>
7247096  7247096                   True                    <NA>
7247097  7247097                   True                    <NA>
7247098  7247098                   True                    <NA>

[7247099 rows x 3 columns]

In [5]:
results_df.dtypes

id                        uint64[pyarrow]
standard_binning_label      bool[pyarrow]
standard_binning_kfold     int32[pyarrow]
dtype: object

In [6]:
bins_iterator = product(zip(et_bins[:-1], et_bins[1:]), zip(eta_bins[:-1], eta_bins[1:]))
for (et_bin_left, et_bin_right), (eta_bin_left, eta_bin_right) in bins_iterator:
    print(f'Processing bin: ET in [{et_bin_left}, {et_bin_right}), ETA in [{eta_bin_left}, {eta_bin_right})')
    current_query = BASE_QEUERY.format(
        et_col=et_col,
        eta_col=eta_col,
        table_data_path=str(dataset_dir / 'data.parquet' / 'data_*.parquet'),
        et_bin_left=int(et_bin_left*1e3),
        et_bin_right=int(et_bin_right*1e3),
        eta_bin_left=eta_bin_left,
        eta_bin_right=eta_bin_right
    )
    logger.debug(f'Executing query:\n{current_query}')
    df = duckdb.query(current_query).fetch_arrow_table().to_pandas(types_mapper=pd.ArrowDtype)
    id_col = df['id'].astype(int)
    label_col = df['standard_binning_label'].astype(int)
    for fold, (_, val_idx) in enumerate(splitter.split(id_col, label_col)):
        print(f'Assigning fold {fold} to {len(val_idx)} samples')
        results_df.loc[results_df['id'].isin(df['id'].iloc[val_idx]), 'standard_binning_kfold'] = fold

Processing bin: ET in [15, 20), ETA in [0, 0.8)
Assigning fold 0 to 44776 samples
Assigning fold 1 to 44776 samples
Assigning fold 2 to 44776 samples
Assigning fold 3 to 44776 samples
Assigning fold 4 to 44775 samples
Processing bin: ET in [15, 20), ETA in [0.8, 1.37)
Assigning fold 0 to 34479 samples
Assigning fold 1 to 34479 samples
Assigning fold 2 to 34479 samples
Assigning fold 3 to 34478 samples
Assigning fold 4 to 34478 samples
Processing bin: ET in [15, 20), ETA in [1.37, 1.52)
Assigning fold 0 to 8044 samples
Assigning fold 1 to 8044 samples
Assigning fold 2 to 8044 samples
Assigning fold 3 to 8044 samples
Assigning fold 4 to 8044 samples
Processing bin: ET in [15, 20), ETA in [1.52, 2.500001)
Assigning fold 0 to 49634 samples
Assigning fold 1 to 49633 samples
Assigning fold 2 to 49633 samples
Assigning fold 3 to 49633 samples
Assigning fold 4 to 49633 samples
Processing bin: ET in [20, 30), ETA in [0, 0.8)
Assigning fold 0 to 47248 samples
Assigning fold 1 to 47248 samples
Assigning fold 2 to 47248 samples
Assigning fold 3 to 47248 samples
Assigning fold 4 to 47248 samples
Processing bin: ET in [20, 30), ETA in [0.8, 1.37)
Assigning fold 0 to 32518 samples
Assigning fold 1 to 32518 samples
Assigning fold 2 to 32517 samples
Assigning fold 3 to 32517 samples
Assigning fold 4 to 32517 samples
Processing bin: ET in [20, 30), ETA in [1.37, 1.52)
Assigning fold 0 to 7931 samples
Assigning fold 1 to 7931 samples
Assigning fold 2 to 7931 samples
Assigning fold 3 to 7931 samples
Assigning fold 4 to 7931 samples
Processing bin: ET in [20, 30), ETA in [1.52, 2.500001)
Assigning fold 0 to 44690 samples
Assigning fold 1 to 44690 samples
Assigning fold 2 to 44689 samples
Assigning fold 3 to 44689 samples
Assigning fold 4 to 44689 samples
Processing bin: ET in [30, 40), ETA in [0, 0.8)
Assigning fold 0 to 62945 samples
Assigning fold 1 to 62945 samples
Assigning fold 2 to 62945 samples
Assigning fold 3 to 62945 samples
Assigning fold 4 to 62945 samples
Processing bin: ET in [30, 40), ETA in [0.8, 1.37)
Assigning fold 0 to 38965 samples
Assigning fold 1 to 38965 samples
Assigning fold 2 to 38965 samples
Assigning fold 3 to 38965 samples
Assigning fold 4 to 38964 samples
Processing bin: ET in [30, 40), ETA in [1.37, 1.52)
Assigning fold 0 to 8933 samples
Assigning fold 1 to 8933 samples
Assigning fold 2 to 8932 samples
Assigning fold 3 to 8932 samples
Assigning fold 4 to 8932 samples
Processing bin: ET in [30, 40), ETA in [1.52, 2.500001)
Assigning fold 0 to 41906 samples
Assigning fold 1 to 41905 samples
Assigning fold 2 to 41905 samples
Assigning fold 3 to 41905 samples
Assigning fold 4 to 41905 samples
Processing bin: ET in [40, 50), ETA in [0, 0.8)
Assigning fold 0 to 64532 samples
Assigning fold 1 to 64532 samples
Assigning fold 2 to 64532 samples
Assigning fold 3 to 64531 samples
Assigning fold 4 to 64531 samples
Processing bin: ET in [40, 50), ETA in [0.8, 1.37)
Assigning fold 0 to 40923 samples
Assigning fold 1 to 40923 samples
Assigning fold 2 to 40923 samples
Assigning fold 3 to 40923 samples
Assigning fold 4 to 40922 samples
Processing bin: ET in [40, 50), ETA in [1.37, 1.52)
Assigning fold 0 to 7368 samples
Assigning fold 1 to 7367 samples
Assigning fold 2 to 7367 samples
Assigning fold 3 to 7367 samples
Assigning fold 4 to 7367 samples
Processing bin: ET in [40, 50), ETA in [1.52, 2.500001)
Assigning fold 0 to 40419 samples
Assigning fold 1 to 40419 samples
Assigning fold 2 to 40419 samples
Assigning fold 3 to 40419 samples
Assigning fold 4 to 40418 samples
Processing bin: ET in [50, 1000000000000), ETA in [0, 0.8)
Assigning fold 0 to 25288 samples
Assigning fold 1 to 25288 samples
Assigning fold 2 to 25288 samples
Assigning fold 3 to 25288 samples
Assigning fold 4 to 25288 samples
Processing bin: ET in [50, 1000000000000), ETA in [0.8, 1.37)
Assigning fold 0 to 16441 samples
Assigning fold 1 to 16441 samples
Assigning fold 2 to 16441 samples
Assigning fold 3 to 16441 samples
Assigning fold 4 to 16441 samples
Processing bin: ET in [50, 1000000000000), ETA in [1.37, 1.52)
Assigning fold 0 to 3241 samples
Assigning fold 1 to 3241 samples
Assigning fold 2 to 3240 samples
Assigning fold 3 to 3240 samples
Assigning fold 4 to 3240 samples
Processing bin: ET in [50, 1000000000000), ETA in [1.52, 2.500001)
Assigning fold 0 to 15675 samples
Assigning fold 1 to 15675 samples
Assigning fold 2 to 15674 samples
Assigning fold 3 to 15674 samples
Assigning fold 4 to 15674 samples

In [7]:
results_df['standard_binning_kfold'] = results_df['standard_binning_kfold'].astype('uint8[pyarrow]')
results_df

              id standard_binning_label  standard_binning_kfold
0              0                  False                       2
1              1                  False                       3
2              2                  False                       4
3              3                  False                    <NA>
4              4                  False                    <NA>
...          ...                    ...                     ...
7247094  7247094                   True                       0
7247095  7247095                   True                       2
7247096  7247096                   True                       2
7247097  7247097                   True                       4
7247098  7247098                   True                       2

[7247099 rows x 3 columns]

In [8]:
results_df.dtypes

id                        uint64[pyarrow]
standard_binning_label      bool[pyarrow]
standard_binning_kfold     uint8[pyarrow]
dtype: object

# Validate

## Check KFold

In [9]:
results_df.value_counts('standard_binning_kfold', dropna=False)

standard_binning_kfold
<NA>    4067354
0        635956
1        635953
2        635948
3        635946
4        635942
Name: count, dtype: int64

## Check Label

In [10]:
results_df.value_counts('standard_binning_label', dropna=False)

standard_binning_label
False    4918564
True     1922802
<NA>      405733
Name: count, dtype: int64

# Saving data

In [11]:
sample_per_batch = 100_000
output_dir = dataset_dir / 'standard_binning_kfold.parquet'
output_dir.mkdir(exist_ok=True)
for file_count, start in enumerate(range(0, len(results_df), sample_per_batch)):
    end = start + sample_per_batch
    if end > len(results_df):
        end = len(results_df)
    print(f'Saving batch {file_count} with samples from index {start} to {end}')
    batch_df = results_df.iloc[start:end]
    batch_path = output_dir / f'standard_binning_kfold_{file_count:04d}.parquet'
    batch_df.to_parquet(batch_path, index=False)

Saving batch 0 with samples from index 0 to 100000
Saving batch 1 with samples from index 100000 to 200000
Saving batch 2 with samples from index 200000 to 300000
Saving batch 3 with samples from index 300000 to 400000
Saving batch 4 with samples from index 400000 to 500000
Saving batch 5 with samples from index 500000 to 600000
Saving batch 6 with samples from index 600000 to 700000
Saving batch 7 with samples from index 700000 to 800000
Saving batch 8 with samples from index 800000 to 900000
Saving batch 9 with samples from index 900000 to 1000000
Saving batch 10 with samples from index 1000000 to 1100000
Saving batch 11 with samples from index 1100000 to 1200000
Saving batch 12 with samples from index 1200000 to 1300000
Saving batch 13 with samples from index 1300000 to 1400000
Saving batch 14 with samples from index 1400000 to 1500000
Saving batch 15 with samples from index 1500000 to 1600000
Saving batch 16 with samples from index 1600000 to 1700000
Saving batch 17 with samples from index 1700000 to 1800000
Saving batch 18 with samples from index 1800000 to 1900000
Saving batch 19 with samples from index 1900000 to 2000000
Saving batch 20 with samples from index 2000000 to 2100000
Saving batch 21 with samples from index 2100000 to 2200000
Saving batch 22 with samples from index 2200000 to 2300000
Saving batch 23 with samples from index 2300000 to 2400000
Saving batch 24 with samples from index 2400000 to 2500000
Saving batch 25 with samples from index 2500000 to 2600000
Saving batch 26 with samples from index 2600000 to 2700000
Saving batch 27 with samples from index 2700000 to 2800000
Saving batch 28 with samples from index 2800000 to 2900000
Saving batch 29 with samples from index 2900000 to 3000000
Saving batch 30 with samples from index 3000000 to 3100000
Saving batch 31 with samples from index 3100000 to 3200000
Saving batch 32 with samples from index 3200000 to 3300000
Saving batch 33 with samples from index 3300000 to 3400000
Saving batch 34 with samples from index 3400000 to 3500000
Saving batch 35 with samples from index 3500000 to 3600000
Saving batch 36 with samples from index 3600000 to 3700000
Saving batch 37 with samples from index 3700000 to 3800000
Saving batch 38 with samples from index 3800000 to 3900000
Saving batch 39 with samples from index 3900000 to 4000000
Saving batch 40 with samples from index 4000000 to 4100000
Saving batch 41 with samples from index 4100000 to 4200000
Saving batch 42 with samples from index 4200000 to 4300000
Saving batch 43 with samples from index 4300000 to 4400000
Saving batch 44 with samples from index 4400000 to 4500000
Saving batch 45 with samples from index 4500000 to 4600000
Saving batch 46 with samples from index 4600000 to 4700000
Saving batch 47 with samples from index 4700000 to 4800000
Saving batch 48 with samples from index 4800000 to 4900000
Saving batch 49 with samples from index 4900000 to 5000000
Saving batch 50 with samples from index 5000000 to 5100000
Saving batch 51 with samples from index 5100000 to 5200000
Saving batch 52 with samples from index 5200000 to 5300000
Saving batch 53 with samples from index 5300000 to 5400000
Saving batch 54 with samples from index 5400000 to 5500000
Saving batch 55 with samples from index 5500000 to 5600000
Saving batch 56 with samples from index 5600000 to 5700000
Saving batch 57 with samples from index 5700000 to 5800000
Saving batch 58 with samples from index 5800000 to 5900000
Saving batch 59 with samples from index 5900000 to 6000000
Saving batch 60 with samples from index 6000000 to 6100000
Saving batch 61 with samples from index 6100000 to 6200000
Saving batch 62 with samples from index 6200000 to 6300000
Saving batch 63 with samples from index 6300000 to 6400000
Saving batch 64 with samples from index 6400000 to 6500000
Saving batch 65 with samples from index 6500000 to 6600000
Saving batch 66 with samples from index 6600000 to 6700000
Saving batch 67 with samples from index 6700000 to 6800000
Saving batch 68 with samples from index 6800000 to 6900000
Saving batch 69 with samples from index 6900000 to 7000000
Saving batch 70 with samples from index 7000000 to 7100000
Saving batch 71 with samples from index 7100000 to 7200000
Saving batch 72 with samples from index 7200000 to 7247099