In [1]:
from pathlib import Path
import duckdb
from sklearn.model_selection import StratifiedKFold
import pandas as pd
from itertools import product
import pandera.pandas as pa
import pyarrow
import os
import sys
sys.path.append(str(Path(os.getcwd()).parent.absolute()))

import colorlog
logger = colorlog.getLogger()

In [2]:
BASE_QEUERY = """
SELECT 
    id,
    target,
    el_lhmedium,
    el_lhvloose,
    IF({et_col} < 0, 0, {et_col}) AS {et_col}_normalized,
    ABS({eta_col}) AS {eta_col}_normalized,
    CASE WHEN el_lhmedium AND target=1 THEN TRUE
         WHEN NOT el_lhvloose AND target=0 THEN FALSE
         ELSE NULL END AS label,
FROM read_parquet('{table_data_path}')
WHERE {et_col}_normalized >= {et_bin_left} AND
      {et_col}_normalized < {et_bin_right} AND
      {eta_col}_normalized >= {eta_bin_left} AND
      {eta_col}_normalized < {eta_bin_right} AND
      label IS NOT NULL;
"""

RESULT_QUERY = """
SELECT
    id,
    CASE WHEN el_lhmedium AND target=1 THEN TRUE
         WHEN NOT el_lhvloose AND target=0 THEN FALSE
         ELSE NULL END AS label,
    NULL AS fold
FROM read_parquet('{table_data_path}');
"""

kfold_dataframe_schema = pa.DataFrameSchema({
    'id': pa.Column(
        pd.ArrowDtype(pyarrow.uint64()),
        unique=True,
        checks=[
            pa.Check.ge(0),
        ]),
    'label': pa.Column(
        pd.ArrowDtype(pyarrow.bool_()),
        nullable=True),
    'fold': pa.Column(
        pd.ArrowDtype(pyarrow.uint8()),
        nullable=True,
        checks=[
            pa.Check.ge(0),
            pa.Check.le(4),
        ])
})

In [3]:
dataset_dir = Path('/media/lucasbanunes/KINGSTON/data/cern-datasets/mc21_isabela_qt_no_restriction')
et_bins = [15, 20, 30, 40, 50, int(1e12)]
et_col = 'trig_L2_calo_et'
eta_bins = [0, 0.8, 1.37, 1.52, 2.500001]
eta_col = 'trig_L2_calo_eta'
splitter = StratifiedKFold(n_splits=5, shuffle=True)

In [4]:
result_query = RESULT_QUERY.format(
    table_data_path=str(dataset_dir / 'data.parquet' / '*.parquet')
)
results_df = duckdb.query(result_query).fetch_arrow_table().to_pandas(types_mapper=pd.ArrowDtype)
results_df

              id  label  fold
0              0  False  <NA>
1              1  False  <NA>
2              2  False  <NA>
3              3  False  <NA>
4              4  False  <NA>
...          ...    ...   ...
7166053  7166053   <NA>  <NA>
7166054  7166054   <NA>  <NA>
7166055  7166055   <NA>  <NA>
7166056  7166056   True  <NA>
7166057  7166057   True  <NA>

[7166058 rows x 3 columns]

In [5]:
results_df.dtypes

id       uint64[pyarrow]
label      bool[pyarrow]
fold      int32[pyarrow]
dtype: object

In [6]:
bins_iterator = product(zip(et_bins[:-1], et_bins[1:]), zip(eta_bins[:-1], eta_bins[1:]))
for (et_bin_left, et_bin_right), (eta_bin_left, eta_bin_right) in bins_iterator:
    print(f'Processing bin: ET in [{et_bin_left}, {et_bin_right}), ETA in [{eta_bin_left}, {eta_bin_right})')
    current_query = BASE_QEUERY.format(
        et_col=et_col,
        eta_col=eta_col,
        table_data_path=str(dataset_dir / 'data.parquet' / 'data_*.parquet'),
        et_bin_left=int(et_bin_left*1e3),
        et_bin_right=int(et_bin_right*1e3),
        eta_bin_left=eta_bin_left,
        eta_bin_right=eta_bin_right
    )
    logger.debug(f'Executing query:\n{current_query}')
    df = duckdb.query(current_query).fetch_arrow_table().to_pandas(types_mapper=pd.ArrowDtype)
    id_col = df['id'].astype(int)
    label_col = df['label'].astype(int)
    for fold, (_, val_idx) in enumerate(splitter.split(id_col.values, label_col.values)):
        print(f'Assigning fold {fold} to {len(val_idx)} samples')
        val_ids = df['id'].iloc[val_idx]
        results_df.loc[results_df['id'].isin(val_ids), 'fold'] = fold

Processing bin: ET in [15, 20), ETA in [0, 0.8)
Assigning fold 0 to 44121 samples
Assigning fold 1 to 44120 samples
Assigning fold 2 to 44120 samples
Assigning fold 3 to 44120 samples
Assigning fold 4 to 44120 samples
Processing bin: ET in [15, 20), ETA in [0.8, 1.37)
Assigning fold 0 to 33948 samples
Assigning fold 1 to 33948 samples
Assigning fold 2 to 33948 samples
Assigning fold 3 to 33948 samples
Assigning fold 4 to 33947 samples
Processing bin: ET in [15, 20), ETA in [1.37, 1.52)
Assigning fold 0 to 7934 samples
Assigning fold 1 to 7934 samples
Assigning fold 2 to 7934 samples
Assigning fold 3 to 7934 samples
Assigning fold 4 to 7933 samples
Processing bin: ET in [15, 20), ETA in [1.52, 2.500001)
Assigning fold 0 to 48912 samples
Assigning fold 1 to 48912 samples
Assigning fold 2 to 48911 samples
Assigning fold 3 to 48911 samples
Assigning fold 4 to 48911 samples
Processing bin: ET in [20, 30), ETA in [0, 0.8)
Assigning fold 0 to 46828 samples
Assigning fold 1 to 46828 samples
Assigning fold 2 to 46828 samples
Assigning fold 3 to 46828 samples
Assigning fold 4 to 46827 samples
Processing bin: ET in [20, 30), ETA in [0.8, 1.37)
Assigning fold 0 to 32175 samples
Assigning fold 1 to 32175 samples
Assigning fold 2 to 32175 samples
Assigning fold 3 to 32174 samples
Assigning fold 4 to 32174 samples
Processing bin: ET in [20, 30), ETA in [1.37, 1.52)
Assigning fold 0 to 7846 samples
Assigning fold 1 to 7846 samples
Assigning fold 2 to 7846 samples
Assigning fold 3 to 7845 samples
Assigning fold 4 to 7845 samples
Processing bin: ET in [20, 30), ETA in [1.52, 2.500001)
Assigning fold 0 to 44222 samples
Assigning fold 1 to 44222 samples
Assigning fold 2 to 44222 samples
Assigning fold 3 to 44221 samples
Assigning fold 4 to 44221 samples
Processing bin: ET in [30, 40), ETA in [0, 0.8)
Assigning fold 0 to 62824 samples
Assigning fold 1 to 62824 samples
Assigning fold 2 to 62824 samples
Assigning fold 3 to 62823 samples
Assigning fold 4 to 62823 samples
Processing bin: ET in [30, 40), ETA in [0.8, 1.37)
Assigning fold 0 to 38868 samples
Assigning fold 1 to 38868 samples
Assigning fold 2 to 38868 samples
Assigning fold 3 to 38868 samples
Assigning fold 4 to 38868 samples
Processing bin: ET in [30, 40), ETA in [1.37, 1.52)
Assigning fold 0 to 8909 samples
Assigning fold 1 to 8908 samples
Assigning fold 2 to 8908 samples
Assigning fold 3 to 8908 samples
Assigning fold 4 to 8908 samples
Processing bin: ET in [30, 40), ETA in [1.52, 2.500001)
Assigning fold 0 to 41777 samples
Assigning fold 1 to 41777 samples
Assigning fold 2 to 41777 samples
Assigning fold 3 to 41777 samples
Assigning fold 4 to 41776 samples
Processing bin: ET in [40, 50), ETA in [0, 0.8)
Assigning fold 0 to 64494 samples
Assigning fold 1 to 64494 samples
Assigning fold 2 to 64494 samples
Assigning fold 3 to 64494 samples
Assigning fold 4 to 64494 samples
Processing bin: ET in [40, 50), ETA in [0.8, 1.37)
Assigning fold 0 to 40891 samples
Assigning fold 1 to 40891 samples
Assigning fold 2 to 40890 samples
Assigning fold 3 to 40890 samples
Assigning fold 4 to 40890 samples
Processing bin: ET in [40, 50), ETA in [1.37, 1.52)
Assigning fold 0 to 7359 samples
Assigning fold 1 to 7359 samples
Assigning fold 2 to 7359 samples
Assigning fold 3 to 7359 samples
Assigning fold 4 to 7359 samples
Processing bin: ET in [40, 50), ETA in [1.52, 2.500001)
Assigning fold 0 to 40372 samples
Assigning fold 1 to 40372 samples
Assigning fold 2 to 40371 samples
Assigning fold 3 to 40371 samples
Assigning fold 4 to 40371 samples
Processing bin: ET in [50, 1000000000000), ETA in [0, 0.8)
Assigning fold 0 to 25242 samples
Assigning fold 1 to 25241 samples
Assigning fold 2 to 25241 samples
Assigning fold 3 to 25241 samples
Assigning fold 4 to 25241 samples
Processing bin: ET in [50, 1000000000000), ETA in [0.8, 1.37)
Assigning fold 0 to 16407 samples
Assigning fold 1 to 16407 samples
Assigning fold 2 to 16406 samples
Assigning fold 3 to 16406 samples
Assigning fold 4 to 16406 samples
Processing bin: ET in [50, 1000000000000), ETA in [1.37, 1.52)
Assigning fold 0 to 3232 samples
Assigning fold 1 to 3232 samples
Assigning fold 2 to 3231 samples
Assigning fold 3 to 3231 samples
Assigning fold 4 to 3231 samples
Processing bin: ET in [50, 1000000000000), ETA in [1.52, 2.500001)
Assigning fold 0 to 15632 samples
Assigning fold 1 to 15631 samples
Assigning fold 2 to 15631 samples
Assigning fold 3 to 15631 samples
Assigning fold 4 to 15631 samples

In [7]:
results_df['fold'] = results_df['fold'].astype('uint8[pyarrow]')
results_df

              id  label  fold
0              0  False  <NA>
1              1  False     1
2              2  False     3
3              3  False     0
4              4  False     4
...          ...    ...   ...
7166053  7166053   <NA>  <NA>
7166054  7166054   <NA>  <NA>
7166055  7166055   <NA>  <NA>
7166056  7166056   True     2
7166057  7166057   True     1

[7166058 rows x 3 columns]

In [8]:
results_df.dtypes

id       uint64[pyarrow]
label      bool[pyarrow]
fold      uint8[pyarrow]
dtype: object

# Validate

In [9]:
results_df = kfold_dataframe_schema.validate(results_df)
results_df

              id  label  fold
0              0  False  <NA>
1              1  False     1
2              2  False     3
3              3  False     0
4              4  False     4
...          ...    ...   ...
7166053  7166053   <NA>  <NA>
7166054  7166054   <NA>  <NA>
7166055  7166055   <NA>  <NA>
7166056  7166056   True     2
7166057  7166057   True     1

[7166058 rows x 3 columns]

# Saving data

In [10]:
sample_per_batch = 100_000
output_dir = dataset_dir / 'standard_binning_kfold.parquet'
output_dir.mkdir(exist_ok=True)
for file_count, start in enumerate(range(0, len(results_df), sample_per_batch)):
    end = start + sample_per_batch
    if end > len(results_df):
        end = len(results_df)
    print(f'Saving batch {file_count} with samples from index {start} to {end}')
    batch_df = results_df.iloc[start:end]
    batch_path = output_dir / f'standard_binning_kfold_{file_count:04d}.parquet'
    batch_df.to_parquet(batch_path, index=False)

Saving batch 0 with samples from index 0 to 100000
Saving batch 1 with samples from index 100000 to 200000
Saving batch 2 with samples from index 200000 to 300000
Saving batch 3 with samples from index 300000 to 400000
Saving batch 4 with samples from index 400000 to 500000
Saving batch 5 with samples from index 500000 to 600000
Saving batch 6 with samples from index 600000 to 700000
Saving batch 7 with samples from index 700000 to 800000
Saving batch 8 with samples from index 800000 to 900000
Saving batch 9 with samples from index 900000 to 1000000
Saving batch 10 with samples from index 1000000 to 1100000
Saving batch 11 with samples from index 1100000 to 1200000
Saving batch 12 with samples from index 1200000 to 1300000
Saving batch 13 with samples from index 1300000 to 1400000
Saving batch 14 with samples from index 1400000 to 1500000
Saving batch 15 with samples from index 1500000 to 1600000
Saving batch 16 with samples from index 1600000 to 1700000
Saving batch 17 with samples from index 1700000 to 1800000
Saving batch 18 with samples from index 1800000 to 1900000
Saving batch 19 with samples from index 1900000 to 2000000
Saving batch 20 with samples from index 2000000 to 2100000
Saving batch 21 with samples from index 2100000 to 2200000
Saving batch 22 with samples from index 2200000 to 2300000
Saving batch 23 with samples from index 2300000 to 2400000
Saving batch 24 with samples from index 2400000 to 2500000
Saving batch 25 with samples from index 2500000 to 2600000
Saving batch 26 with samples from index 2600000 to 2700000
Saving batch 27 with samples from index 2700000 to 2800000
Saving batch 28 with samples from index 2800000 to 2900000
Saving batch 29 with samples from index 2900000 to 3000000
Saving batch 30 with samples from index 3000000 to 3100000
Saving batch 31 with samples from index 3100000 to 3200000
Saving batch 32 with samples from index 3200000 to 3300000
Saving batch 33 with samples from index 3300000 to 3400000
Saving batch 34 with samples from index 3400000 to 3500000
Saving batch 35 with samples from index 3500000 to 3600000
Saving batch 36 with samples from index 3600000 to 3700000
Saving batch 37 with samples from index 3700000 to 3800000
Saving batch 38 with samples from index 3800000 to 3900000
Saving batch 39 with samples from index 3900000 to 4000000
Saving batch 40 with samples from index 4000000 to 4100000
Saving batch 41 with samples from index 4100000 to 4200000
Saving batch 42 with samples from index 4200000 to 4300000
Saving batch 43 with samples from index 4300000 to 4400000
Saving batch 44 with samples from index 4400000 to 4500000
Saving batch 45 with samples from index 4500000 to 4600000
Saving batch 46 with samples from index 4600000 to 4700000
Saving batch 47 with samples from index 4700000 to 4800000
Saving batch 48 with samples from index 4800000 to 4900000
Saving batch 49 with samples from index 4900000 to 5000000
Saving batch 50 with samples from index 5000000 to 5100000
Saving batch 51 with samples from index 5100000 to 5200000
Saving batch 52 with samples from index 5200000 to 5300000
Saving batch 53 with samples from index 5300000 to 5400000
Saving batch 54 with samples from index 5400000 to 5500000
Saving batch 55 with samples from index 5500000 to 5600000
Saving batch 56 with samples from index 5600000 to 5700000
Saving batch 57 with samples from index 5700000 to 5800000
Saving batch 58 with samples from index 5800000 to 5900000
Saving batch 59 with samples from index 5900000 to 6000000
Saving batch 60 with samples from index 6000000 to 6100000
Saving batch 61 with samples from index 6100000 to 6200000
Saving batch 62 with samples from index 6200000 to 6300000
Saving batch 63 with samples from index 6300000 to 6400000
Saving batch 64 with samples from index 6400000 to 6500000
Saving batch 65 with samples from index 6500000 to 6600000
Saving batch 66 with samples from index 6600000 to 6700000
Saving batch 67 with samples from index 6700000 to 6800000
Saving batch 68 with samples from index 6800000 to 6900000
Saving batch 69 with samples from index 6900000 to 7000000
Saving batch 70 with samples from index 7000000 to 7100000
Saving batch 71 with samples from index 7100000 to 7166058