In [ ]:
from pathlib import Path
from tempfile import TemporaryDirectory
import tarfile
import pandas as pd
import pyarrow
import pandera.pandas as pa
import numpy as np
import duckdb
import os
import sys
sys.path.append(str(Path(os.getcwd()).parent.absolute()))
import colorlog
logger = colorlog.getLogger()

from ringer_zero.root import read_ttree_as_pdf
TTREE_NAME = 'run_410000/HLT/EgammaMon/summary/events'

In [43]:
source_files = {
    'jf17': {
        'datapath': Path(
            '/media/lucasbanunes/KINGSTON/data/cern-datasets/mc21_isabela_qt_no_restriction/source/bkg/user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_without_sigma_constraint_31.10.23_v0_EXT0.tap_jf17_5M_XYZ.root.tgz'
        ),
        'target': 0
    },
    'zee': {
        'datapath': Path(
            '/media/lucasbanunes/KINGSTON/data/cern-datasets/mc21_isabela_qt_no_restriction/source/signal/user.isilvafe.mc21_13p6TeV.Zee.AOD.r14136_2sigma_constraint_26.10.23_v0_EXT0.tap_zee_5M_XYZ.root.tgz'
        ),
        'target': 1
    }
}
samples_per_batch = 100000
output_dir = Path('/media/lucasbanunes/KINGSTON/data/cern-datasets/mc21_isabela_qt_no_restriction/data.parquet')
if output_dir.exists():
    logger.warning(f'Output directory {output_dir} already exists. Files may be overwritten.')
else:
    output_dir.mkdir(parents=True, exist_ok=True)

In [3]:
def is_safe_int8_cast(series: pd.Series):
    unique_values = series.unique().to_numpy()
    if np.any(np.logical_and(unique_values != 0, unique_values != 1)):
        raise ValueError(f"Series must contain only 1's and 0's for int8 casting, found {unique_values}")
    return True


INT8_CASTS = [
    'el_lhtight',
    'el_lhmedium',
    'el_lhloose',
    'el_lhvloose',
    'el_dnntight',
    'el_dnnmedium',
    'el_dnnloose',
    'mc_hasMC',
    'mc_isTruthElectronAny',
    'mc_isTruthElectronFromZ',
    'mc_isTruthElectronFromJpsiPrompt'
]

def dump_df(df, file_count, processed_rows, output_dir):
    logger.info(f'Processing Batch {file_count} (Rows {processed_rows} to {processed_rows + len(df)})')
    output_path = output_dir / f'data_{file_count:04d}.parquet'
    df['id'] = pd.Series(range(processed_rows, processed_rows + len(df)), dtype="uint64[pyarrow]")
    for col in INT8_CASTS:
        is_safe_int8_cast(df[col])
        df[col] = df[col].astype('bool[pyarrow]')
    df.to_parquet(output_path, index=False)
    return file_count + 1, processed_rows + len(df)

In [4]:
df_accumulator = pd.DataFrame()
file_count = 0
processed_rows = 0

for sample_name, sample_info in source_files.items():
    for root_tar in sample_info['datapath'].glob('*.root.tgz'):
        logger.info(f'Reading {root_tar} for sample {sample_name}')
        with TemporaryDirectory() as temp_dir:
            temp_dir_path = Path(temp_dir)
            with tarfile.open(root_tar, 'r:gz') as tar:
                tar.extractall(path=temp_dir_path)
            for root_file in temp_dir_path.glob('*.root'):
                logger.info(f'Reading {root_file} for sample {sample_name}')
                df = read_ttree_as_pdf(root_file, ttree_name='run_410000/HLT/EgammaMon/summary/events')
                df['target'] = sample_info['target']
                df['target'] = df['target'].astype('uint8[pyarrow]')
                df_accumulator = pd.concat([df_accumulator, df], ignore_index=True)
                if len(df_accumulator) >= samples_per_batch:
                    file_count, processed_rows = dump_df(
                        df_accumulator, file_count, processed_rows, output_dir
                    )
                    df_accumulator = pd.DataFrame()  # Reset accumulator

if len(df_accumulator):
    file_count, processed_rows = dump_df(
        df_accumulator, file_count, processed_rows, output_dir
    )

 [Sun, 15 Mar 2026 22:46:36] INFO Reading /media/lucasbanunes/KINGSTON/data/cern-datasets/mc21_isabela_qt_no_restriction/source/bkg/user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_without_sigma_constraint_31.10.23_v0_EXT0.tap_jf17_5M_XYZ.root.tgz/user.isilvafe.35450371._000001.XYZ.root.tgz for sample jf17
/tmp/ipykernel_1094136/3714514901.py:11: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 22:46:36] INFO Reading /tmp/tmpm7lak3e0/output.35450371._000002.root for sample jf17
 [Sun, 15 Mar 2026 22:46:36] INFO Reading /tmp/tmpm7lak3e0/output.35450371._000010.root for sample jf17
 [Sun, 15 Mar 2026 22:46:37] INFO Reading /tmp/tmpm7lak3e0/output.35450371._000004.root for sample jf17
 [Sun, 15 Mar 2026 22:46:37] INFO Reading /tmp/tmpm7lak3e0/output.35450371._000009.root for sample jf17
 [Sun, 15 Mar 2026 22:46:37] INFO Reading /tmp/tmpm7lak3e0/output.35450371._000008.root for sample jf17
 [Sun, 15 Mar 2026 22:46:38] INFO Reading /tmp/tmpm7lak3e0/output.35450371._000006.root for sample jf17
 [Sun, 15 Mar 2026 22:46:38] INFO Reading /tmp/tmpm7lak3e0/output.35450371._000007.root for sample jf17
 [Sun, 15 Mar 2026 22:46:38] INFO Reading /tmp/tmpm7lak3e0/output.35450371._000001.root for sample jf17
 [Sun, 15 Mar 2026 22:46:38] INFO Reading /tmp/tmpm7lak3e0/output.35450371._000003.root for sample jf17
 [Sun, 15 Mar 2026 22:46:39] INFO Reading /tmp/tmpm7lak3e0/output.35450371._000005.root for sample jf17
 [Sun, 15 Mar 2026 22:46:39] INFO Processing Batch 0 (Rows 0 to 102182)
 [Sun, 15 Mar 2026 22:46:40] INFO Reading /media/lucasbanunes/KINGSTON/data/cern-datasets/mc21_isabela_qt_no_restriction/source/bkg/user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_without_sigma_constraint_31.10.23_v0_EXT0.tap_jf17_5M_XYZ.root.tgz/user.isilvafe.35450371._000002.XYZ.root.tgz for sample jf17
/tmp/ipykernel_1094136/3714514901.py:11: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 22:46:40] INFO Reading /tmp/tmpj0ahvby_/output.35450371._000501.root for sample jf17
 [Sun, 15 Mar 2026 22:46:40] INFO Reading /media/lucasbanunes/KINGSTON/data/cern-datasets/mc21_isabela_qt_no_restriction/source/bkg/user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_without_sigma_constraint_31.10.23_v0_EXT0.tap_jf17_5M_XYZ.root.tgz/user.isilvafe.35450371._000003.XYZ.root.tgz for sample jf17
/tmp/ipykernel_1094136/3714514901.py:11: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 22:46:40] INFO Reading /tmp/tmpnoop1qyj/output.35450371._000491.root for sample jf17
 [Sun, 15 Mar 2026 22:46:41] INFO Reading /media/lucasbanunes/KINGSTON/data/cern-datasets/mc21_isabela_qt_no_restriction/source/bkg/user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_without_sigma_constraint_31.10.23_v0_EXT0.tap_jf17_5M_XYZ.root.tgz/user.isilvafe.35450371._000004.XYZ.root.tgz for sample jf17
/tmp/ipykernel_1094136/3714514901.py:11: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 22:46:41] INFO Reading /tmp/tmp84u6e4te/output.35450371._000215.root for sample jf17
 [Sun, 15 Mar 2026 22:46:41] INFO Reading /tmp/tmp84u6e4te/output.35450371._000219.root for sample jf17
 [Sun, 15 Mar 2026 22:46:41] INFO Reading /tmp/tmp84u6e4te/output.35450371._000216.root for sample jf17
 [Sun, 15 Mar 2026 22:46:42] INFO Reading /tmp/tmp84u6e4te/output.35450371._000217.root for sample jf17
 [Sun, 15 Mar 2026 22:46:42] INFO Reading /tmp/tmp84u6e4te/output.35450371._000220.root for sample jf17
 [Sun, 15 Mar 2026 22:46:42] INFO Reading /tmp/tmp84u6e4te/output.35450371._000218.root for sample jf17
 [Sun, 15 Mar 2026 22:46:43] INFO Reading /tmp/tmp84u6e4te/output.35450371._000222.root for sample jf17
 [Sun, 15 Mar 2026 22:46:43] INFO Reading /tmp/tmp84u6e4te/output.35450371._000221.root for sample jf17
 [Sun, 15 Mar 2026 22:46:43] INFO Processing Batch 1 (Rows 102182 to 204094)
 [Sun, 15 Mar 2026 22:46:44] INFO Reading /media/lucasbanunes/KINGSTON/data/cern-datasets/mc21_isabela_qt_no_restriction/source/bkg/user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_without_sigma_constraint_31.10.23_v0_EXT0.tap_jf17_5M_XYZ.root.tgz/user.isilvafe.35450371._000007.XYZ.root.tgz for sample jf17
/tmp/ipykernel_1094136/3714514901.py:11: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 22:46:45] INFO Reading /tmp/tmp76533fu4/output.35450371._000081.root for sample jf17
 [Sun, 15 Mar 2026 22:46:45] INFO Reading /tmp/tmp76533fu4/output.35450371._000066.root for sample jf17
 [Sun, 15 Mar 2026 22:46:46] INFO Reading /tmp/tmp76533fu4/output.35450371._000064.root for sample jf17
 [Sun, 15 Mar 2026 22:46:46] INFO Reading /tmp/tmp76533fu4/output.35450371._000072.root for sample jf17
 [Sun, 15 Mar 2026 22:46:46] INFO Reading /tmp/tmp76533fu4/output.35450371._000068.root for sample jf17
 [Sun, 15 Mar 2026 22:46:47] INFO Reading /tmp/tmp76533fu4/output.35450371._000074.root for sample jf17
 [Sun, 15 Mar 2026 22:46:47] INFO Reading /tmp/tmp76533fu4/output.35450371._000076.root for sample jf17
 [Sun, 15 Mar 2026 22:46:47] INFO Reading /tmp/tmp76533fu4/output.35450371._000063.root for sample jf17
 [Sun, 15 Mar 2026 22:46:47] INFO Reading /tmp/tmp76533fu4/output.35450371._000071.root for sample jf17
 [Sun, 15 Mar 2026 22:46:48] INFO Reading /tmp/tmp76533fu4/output.35450371._000065.root for sample jf17
 [Sun, 15 Mar 2026 22:46:48] INFO Processing Batch 2 (Rows 204094 to 305901)
 [Sun, 15 Mar 2026 22:46:49] INFO Reading /tmp/tmp76533fu4/output.35450371._000078.root for sample jf17
 [Sun, 15 Mar 2026 22:46:49] INFO Reading /tmp/tmp76533fu4/output.35450371._000080.root for sample jf17
 [Sun, 15 Mar 2026 22:46:50] INFO Reading /tmp/tmp76533fu4/output.35450371._000069.root for sample jf17
 [Sun, 15 Mar 2026 22:46:50] INFO Reading /tmp/tmp76533fu4/output.35450371._000062.root for sample jf17
 [Sun, 15 Mar 2026 22:46:50] INFO Reading /tmp/tmp76533fu4/output.35450371._000083.root for sample jf17
 [Sun, 15 Mar 2026 22:46:50] INFO Reading /tmp/tmp76533fu4/output.35450371._000079.root for sample jf17
 [Sun, 15 Mar 2026 22:46:51] INFO Reading /tmp/tmp76533fu4/output.35450371._000077.root for sample jf17
 [Sun, 15 Mar 2026 22:46:51] INFO Reading /tmp/tmp76533fu4/output.35450371._000061.root for sample jf17
 [Sun, 15 Mar 2026 22:46:51] INFO Reading /tmp/tmp76533fu4/output.35450371._000070.root for sample jf17
 [Sun, 15 Mar 2026 22:46:52] INFO Reading /tmp/tmp76533fu4/output.35450371._000075.root for sample jf17
 [Sun, 15 Mar 2026 22:46:52] INFO Processing Batch 3 (Rows 305901 to 407451)
 [Sun, 15 Mar 2026 22:46:53] INFO Reading /tmp/tmp76533fu4/output.35450371._000073.root for sample jf17
 [Sun, 15 Mar 2026 22:46:53] INFO Reading /tmp/tmp76533fu4/output.35450371._000082.root for sample jf17
 [Sun, 15 Mar 2026 22:46:54] INFO Reading /tmp/tmp76533fu4/output.35450371._000067.root for sample jf17
 [Sun, 15 Mar 2026 22:46:54] INFO Reading /media/lucasbanunes/KINGSTON/data/cern-datasets/mc21_isabela_qt_no_restriction/source/bkg/user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_without_sigma_constraint_31.10.23_v0_EXT0.tap_jf17_5M_XYZ.root.tgz/user.isilvafe.35450371._000008.XYZ.root.tgz for sample jf17
/tmp/ipykernel_1094136/3714514901.py:11: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 22:46:55] INFO Reading /tmp/tmp7__s88mn/output.35450371._000234.root for sample jf17
 [Sun, 15 Mar 2026 22:46:55] INFO Reading /tmp/tmp7__s88mn/output.35450371._000245.root for sample jf17
 [Sun, 15 Mar 2026 22:46:56] INFO Reading /tmp/tmp7__s88mn/output.35450371._000239.root for sample jf17
 [Sun, 15 Mar 2026 22:46:56] INFO Reading /tmp/tmp7__s88mn/output.35450371._000238.root for sample jf17
 [Sun, 15 Mar 2026 22:46:56] INFO Reading /tmp/tmp7__s88mn/output.35450371._000232.root for sample jf17
 [Sun, 15 Mar 2026 22:46:57] INFO Reading /tmp/tmp7__s88mn/output.35450371._000252.root for sample jf17
 [Sun, 15 Mar 2026 22:46:57] INFO Reading /tmp/tmp7__s88mn/output.35450371._000226.root for sample jf17
 [Sun, 15 Mar 2026 22:46:57] INFO Processing Batch 4 (Rows 407451 to 508227)
 [Sun, 15 Mar 2026 22:46:58] INFO Reading /tmp/tmp7__s88mn/output.35450371._000248.root for sample jf17
 [Sun, 15 Mar 2026 22:46:58] INFO Reading /tmp/tmp7__s88mn/output.35450371._000237.root for sample jf17
 [Sun, 15 Mar 2026 22:46:59] INFO Reading /tmp/tmp7__s88mn/output.35450371._000242.root for sample jf17
 [Sun, 15 Mar 2026 22:46:59] INFO Reading /tmp/tmp7__s88mn/output.35450371._000244.root for sample jf17
 [Sun, 15 Mar 2026 22:46:59] INFO Reading /tmp/tmp7__s88mn/output.35450371._000250.root for sample jf17
 [Sun, 15 Mar 2026 22:47:00] INFO Reading /tmp/tmp7__s88mn/output.35450371._000230.root for sample jf17
 [Sun, 15 Mar 2026 22:47:00] INFO Reading /tmp/tmp7__s88mn/output.35450371._000236.root for sample jf17
 [Sun, 15 Mar 2026 22:47:00] INFO Reading /tmp/tmp7__s88mn/output.35450371._000235.root for sample jf17
 [Sun, 15 Mar 2026 22:47:01] INFO Reading /tmp/tmp7__s88mn/output.35450371._000240.root for sample jf17
 [Sun, 15 Mar 2026 22:47:01] INFO Reading /tmp/tmp7__s88mn/output.35450371._000241.root for sample jf17
 [Sun, 15 Mar 2026 22:47:01] INFO Processing Batch 5 (Rows 508227 to 609780)
 [Sun, 15 Mar 2026 22:47:02] INFO Reading /tmp/tmp7__s88mn/output.35450371._000233.root for sample jf17
 [Sun, 15 Mar 2026 22:47:03] INFO Reading /tmp/tmp7__s88mn/output.35450371._000229.root for sample jf17
 [Sun, 15 Mar 2026 22:47:03] INFO Reading /tmp/tmp7__s88mn/output.35450371._000251.root for sample jf17
 [Sun, 15 Mar 2026 22:47:03] INFO Reading /tmp/tmp7__s88mn/output.35450371._000246.root for sample jf17
 [Sun, 15 Mar 2026 22:47:04] INFO Reading /tmp/tmp7__s88mn/output.35450371._000224.root for sample jf17
 [Sun, 15 Mar 2026 22:47:04] INFO Reading /tmp/tmp7__s88mn/output.35450371._000247.root for sample jf17
 [Sun, 15 Mar 2026 22:47:04] INFO Reading /tmp/tmp7__s88mn/output.35450371._000223.root for sample jf17
 [Sun, 15 Mar 2026 22:47:05] INFO Reading /tmp/tmp7__s88mn/output.35450371._000225.root for sample jf17
 [Sun, 15 Mar 2026 22:47:05] INFO Reading /tmp/tmp7__s88mn/output.35450371._000227.root for sample jf17
 [Sun, 15 Mar 2026 22:47:05] INFO Reading /tmp/tmp7__s88mn/output.35450371._000231.root for sample jf17
 [Sun, 15 Mar 2026 22:47:06] INFO Processing Batch 6 (Rows 609780 to 710888)
 [Sun, 15 Mar 2026 22:47:07] INFO Reading /tmp/tmp7__s88mn/output.35450371._000243.root for sample jf17
 [Sun, 15 Mar 2026 22:47:07] INFO Reading /tmp/tmp7__s88mn/output.35450371._000228.root for sample jf17
 [Sun, 15 Mar 2026 22:47:07] INFO Reading /tmp/tmp7__s88mn/output.35450371._000249.root for sample jf17
 [Sun, 15 Mar 2026 22:47:08] INFO Reading /media/lucasbanunes/KINGSTON/data/cern-datasets/mc21_isabela_qt_no_restriction/source/bkg/user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_without_sigma_constraint_31.10.23_v0_EXT0.tap_jf17_5M_XYZ.root.tgz/user.isilvafe.35450371._000009.XYZ.root.tgz for sample jf17
/tmp/ipykernel_1094136/3714514901.py:11: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 22:47:08] INFO Reading /tmp/tmpjqafoyum/output.35450371._000610.root for sample jf17
 [Sun, 15 Mar 2026 22:47:08] INFO Reading /media/lucasbanunes/KINGSTON/data/cern-datasets/mc21_isabela_qt_no_restriction/source/bkg/user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_without_sigma_constraint_31.10.23_v0_EXT0.tap_jf17_5M_XYZ.root.tgz/user.isilvafe.35450371._000010.XYZ.root.tgz for sample jf17
/tmp/ipykernel_1094136/3714514901.py:11: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 22:47:08] INFO Reading /tmp/tmpd70mo96v/output.35450371._000611.root for sample jf17
 [Sun, 15 Mar 2026 22:47:08] INFO Reading /media/lucasbanunes/KINGSTON/data/cern-datasets/mc21_isabela_qt_no_restriction/source/bkg/user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_without_sigma_constraint_31.10.23_v0_EXT0.tap_jf17_5M_XYZ.root.tgz/user.isilvafe.35450371._000011.XYZ.root.tgz for sample jf17
/tmp/ipykernel_1094136/3714514901.py:11: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 22:47:08] INFO Reading /tmp/tmpjiyq3lti/output.35450371._000613.root for sample jf17
 [Sun, 15 Mar 2026 22:47:09] INFO Reading /media/lucasbanunes/KINGSTON/data/cern-datasets/mc21_isabela_qt_no_restriction/source/bkg/user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_without_sigma_constraint_31.10.23_v0_EXT0.tap_jf17_5M_XYZ.root.tgz/user.isilvafe.35450371._000012.XYZ.root.tgz for sample jf17
/tmp/ipykernel_1094136/3714514901.py:11: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 22:47:11] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000053.root for sample jf17
 [Sun, 15 Mar 2026 22:47:11] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000049.root for sample jf17
 [Sun, 15 Mar 2026 22:47:12] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000047.root for sample jf17
 [Sun, 15 Mar 2026 22:47:12] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000041.root for sample jf17
 [Sun, 15 Mar 2026 22:47:12] INFO Processing Batch 7 (Rows 710888 to 812912)
 [Sun, 15 Mar 2026 22:47:13] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000016.root for sample jf17
 [Sun, 15 Mar 2026 22:47:14] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000013.root for sample jf17
 [Sun, 15 Mar 2026 22:47:14] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000019.root for sample jf17
 [Sun, 15 Mar 2026 22:47:14] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000031.root for sample jf17
 [Sun, 15 Mar 2026 22:47:15] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000030.root for sample jf17
 [Sun, 15 Mar 2026 22:47:15] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000043.root for sample jf17
 [Sun, 15 Mar 2026 22:47:15] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000056.root for sample jf17
 [Sun, 15 Mar 2026 22:47:15] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000059.root for sample jf17
 [Sun, 15 Mar 2026 22:47:16] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000050.root for sample jf17
 [Sun, 15 Mar 2026 22:47:16] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000023.root for sample jf17
 [Sun, 15 Mar 2026 22:47:16] INFO Processing Batch 8 (Rows 812912 to 914829)
 [Sun, 15 Mar 2026 22:47:17] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000011.root for sample jf17
 [Sun, 15 Mar 2026 22:47:18] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000021.root for sample jf17
 [Sun, 15 Mar 2026 22:47:18] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000045.root for sample jf17
 [Sun, 15 Mar 2026 22:47:18] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000015.root for sample jf17
 [Sun, 15 Mar 2026 22:47:18] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000042.root for sample jf17
 [Sun, 15 Mar 2026 22:47:19] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000033.root for sample jf17
 [Sun, 15 Mar 2026 22:47:19] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000018.root for sample jf17
 [Sun, 15 Mar 2026 22:47:19] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000024.root for sample jf17
 [Sun, 15 Mar 2026 22:47:20] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000060.root for sample jf17
 [Sun, 15 Mar 2026 22:47:20] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000052.root for sample jf17
 [Sun, 15 Mar 2026 22:47:20] INFO Processing Batch 9 (Rows 914829 to 1016502)
 [Sun, 15 Mar 2026 22:47:21] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000035.root for sample jf17
 [Sun, 15 Mar 2026 22:47:22] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000039.root for sample jf17
 [Sun, 15 Mar 2026 22:47:22] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000051.root for sample jf17
 [Sun, 15 Mar 2026 22:47:22] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000029.root for sample jf17
 [Sun, 15 Mar 2026 22:47:22] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000054.root for sample jf17
 [Sun, 15 Mar 2026 22:47:23] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000014.root for sample jf17
 [Sun, 15 Mar 2026 22:47:23] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000034.root for sample jf17
 [Sun, 15 Mar 2026 22:47:23] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000025.root for sample jf17
 [Sun, 15 Mar 2026 22:47:24] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000032.root for sample jf17
 [Sun, 15 Mar 2026 22:47:24] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000040.root for sample jf17
 [Sun, 15 Mar 2026 22:47:24] INFO Processing Batch 10 (Rows 1016502 to 1118291)
 [Sun, 15 Mar 2026 22:47:25] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000044.root for sample jf17
 [Sun, 15 Mar 2026 22:47:25] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000036.root for sample jf17
 [Sun, 15 Mar 2026 22:47:26] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000017.root for sample jf17
 [Sun, 15 Mar 2026 22:47:26] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000046.root for sample jf17
 [Sun, 15 Mar 2026 22:47:26] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000020.root for sample jf17
 [Sun, 15 Mar 2026 22:47:27] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000058.root for sample jf17
 [Sun, 15 Mar 2026 22:47:27] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000027.root for sample jf17
 [Sun, 15 Mar 2026 22:47:27] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000026.root for sample jf17
 [Sun, 15 Mar 2026 22:47:28] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000048.root for sample jf17
 [Sun, 15 Mar 2026 22:47:28] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000037.root for sample jf17
 [Sun, 15 Mar 2026 22:47:28] INFO Processing Batch 11 (Rows 1118291 to 1220335)
 [Sun, 15 Mar 2026 22:47:29] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000028.root for sample jf17
 [Sun, 15 Mar 2026 22:47:30] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000038.root for sample jf17
 [Sun, 15 Mar 2026 22:47:30] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000012.root for sample jf17
 [Sun, 15 Mar 2026 22:47:30] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000055.root for sample jf17
 [Sun, 15 Mar 2026 22:47:30] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000022.root for sample jf17
 [Sun, 15 Mar 2026 22:47:31] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000057.root for sample jf17
 [Sun, 15 Mar 2026 22:47:31] INFO Reading /media/lucasbanunes/KINGSTON/data/cern-datasets/mc21_isabela_qt_no_restriction/source/bkg/user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_without_sigma_constraint_31.10.23_v0_EXT0.tap_jf17_5M_XYZ.root.tgz/user.isilvafe.35450371._000014.XYZ.root.tgz for sample jf17

# Validate Dataset

In [5]:
output_path_glob = output_dir / 'data_*.parquet'
print(str(output_path_glob))

/media/lucasbanunes/KINGSTON/data/cern-datasets/mc21_isabela_qt_no_restriction/data.parquet/data_*.parquet

## Check Target

In [6]:
target_query = f"""
SELECT
    COALESCE(CAST(target AS VARCHAR), 'NULL') AS value,
    COUNT(*) as count
FROM read_parquet('{str(output_path_glob)}')
GROUP BY target
ORDER BY target ASC;
"""
print(target_query)

SELECT
    COALESCE(CAST(target AS VARCHAR), 'NULL') AS value,
    COUNT(*) as count
FROM read_parquet('/media/lucasbanunes/KINGSTON/data/cern-datasets/mc21_isabela_qt_no_restriction/data.parquet/data_*.parquet')
GROUP BY target
ORDER BY target ASC;

In [7]:
with duckdb.connect(':memory:') as conn:
    df = conn.execute(target_query).fetch_arrow_table().to_pandas(types_mapper=pd.ArrowDtype)
# df.value_counts(dropna=False)
df

  value    count
0     0  4988951
1     1  2177107

## Check ID

In [8]:
id_query = f"""
SELECT
    COALESCE(CAST(id AS VARCHAR), 'NULL') AS value,
    COUNT(*) as count
FROM read_parquet('{str(output_path_glob)}')
GROUP BY id
ORDER BY id ASC;
"""

In [12]:
with duckdb.connect(':memory:') as conn:
    df = conn.execute(id_query).fetch_arrow_table().to_pandas(types_mapper=pd.ArrowDtype)
# df.value_counts(dropna=False)
df

           value  count
0              0      1
1              1      1
2              2      1
3              3      1
4              4      1
...          ...    ...
7166053  7166053      1
7166054  7166054      1
7166055  7166055      1
7166056  7166056      1
7166057  7166057      1

[7166058 rows x 2 columns]

In [13]:
df[df['count'] != 1]

Empty DataFrame
Columns: [value, count]
Index: []

# Convert Reference

In [1]:
import json
from collections import defaultdict
import pandas as pd

In [2]:
ref_path = '/media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/qt_data_mc21_5m/mc21_13p6TeV.Run3_v1.40bins.ref.json'

In [3]:
with open(ref_path, 'r') as f:
    ref = json.load(f)
ref

[[{'tight': {'det': {'total': 232913, 'passed': 232060},
    'fake': {'total': 1946524, 'passed': 435731}},
   'medium': {'det': {'total': 232913, 'passed': 232106},
    'fake': {'total': 1946524, 'passed': 449170}},
   'loose': {'det': {'total': 232913, 'passed': 232102},
    'fake': {'total': 1946524, 'passed': 448182}},
   'vloose': {'det': {'total': 232913, 'passed': 232150},
    'fake': {'total': 1946524, 'passed': 464211}}},
  {'tight': {'det': {'total': 73327, 'passed': 72911},
    'fake': {'total': 1912796, 'passed': 464002}},
   'medium': {'det': {'total': 73327, 'passed': 72926},
    'fake': {'total': 1912796, 'passed': 474462}},
   'loose': {'det': {'total': 73327, 'passed': 72952},
    'fake': {'total': 1912796, 'passed': 494841}},
   'vloose': {'det': {'total': 73327, 'passed': 72961},
    'fake': {'total': 1912796, 'passed': 504975}}},
  {'tight': {'det': {'total': 3205, 'passed': 3010},
    'fake': {'total': 936912, 'passed': 131386}},
   'medium': {'det': {'total': 3205, 'passed': 3042},
    'fake': {'total': 936912, 'passed': 143329}},
   'loose': {'det': {'total': 3205, 'passed': 3043},
    'fake': {'total': 936912, 'passed': 144110}},
   'vloose': {'det': {'total': 3205, 'passed': 3056},
    'fake': {'total': 936912, 'passed': 157041}}},
  {'tight': {'det': {'total': 54069, 'passed': 52272},
    'fake': {'total': 1927127, 'passed': 207715}},
   'medium': {'det': {'total': 54069, 'passed': 52467},
    'fake': {'total': 1927127, 'passed': 218300}},
   'loose': {'det': {'total': 54069, 'passed': 52535},
    'fake': {'total': 1927127, 'passed': 223883}},
   'vloose': {'det': {'total': 54069, 'passed': 52593},
    'fake': {'total': 1927127, 'passed': 226966}}},
  {'tight': {'det': {'total': 3694, 'passed': 3625},
    'fake': {'total': 530772, 'passed': 65917}},
   'medium': {'det': {'total': 3694, 'passed': 3631},
    'fake': {'total': 530772, 'passed': 68158}},
   'loose': {'det': {'total': 3694, 'passed': 3632},
    'fake': {'total': 530772, 'passed': 68653}},
   'vloose': {'det': {'total': 3694, 'passed': 3632},
    'fake': {'total': 530772, 'passed': 68687}}}],
 [{'tight': {'det': {'total': 132921, 'passed': 132518},
    'fake': {'total': 1963194, 'passed': 530493}},
   'medium': {'det': {'total': 132921, 'passed': 132526},
    'fake': {'total': 1963194, 'passed': 547578}},
   'loose': {'det': {'total': 132921, 'passed': 132530},
    'fake': {'total': 1963194, 'passed': 556101}},
   'vloose': {'det': {'total': 132921, 'passed': 132530},
    'fake': {'total': 1963194, 'passed': 557466}}},
  {'tight': {'det': {'total': 51488, 'passed': 51243},
    'fake': {'total': 1939077, 'passed': 456128}},
   'medium': {'det': {'total': 51488, 'passed': 51243},
    'fake': {'total': 1939077, 'passed': 456128}},
   'loose': {'det': {'total': 51488, 'passed': 51240},
    'fake': {'total': 1939077, 'passed': 448309}},
   'vloose': {'det': {'total': 51488, 'passed': 51250},
    'fake': {'total': 1939077, 'passed': 463446}}},
  {'tight': {'det': {'total': 3039, 'passed': 2856},
    'fake': {'total': 1492017, 'passed': 164794}},
   'medium': {'det': {'total': 3039, 'passed': 2856},
    'fake': {'total': 1492017, 'passed': 165295}},
   'loose': {'det': {'total': 3039, 'passed': 2857},
    'fake': {'total': 1492017, 'passed': 165646}},
   'vloose': {'det': {'total': 3039, 'passed': 2864},
    'fake': {'total': 1492017, 'passed': 171130}}},
  {'tight': {'det': {'total': 31538, 'passed': 30724},
    'fake': {'total': 1956239, 'passed': 147982}},
   'medium': {'det': {'total': 31538, 'passed': 30807},
    'fake': {'total': 1956239, 'passed': 157614}},
   'loose': {'det': {'total': 31538, 'passed': 30831},
    'fake': {'total': 1956239, 'passed': 159144}},
   'vloose': {'det': {'total': 31538, 'passed': 30863},
    'fake': {'total': 1956239, 'passed': 163497}}},
  {'tight': {'det': {'total': 2541, 'passed': 2515},
    'fake': {'total': 773678, 'passed': 74926}},
   'medium': {'det': {'total': 2541, 'passed': 2515},
    'fake': {'total': 773678, 'passed': 74987}},
   'loose': {'det': {'total': 2541, 'passed': 2515},
    'fake': {'total': 773678, 'passed': 74987}},
   'vloose': {'det': {'total': 2541, 'passed': 2515},
    'fake': {'total': 773678, 'passed': 74987}}}],
 [{'tight': {'det': {'total': 64972, 'passed': 64678},
    'fake': {'total': 1958472, 'passed': 374198}},
   'medium': {'det': {'total': 64972, 'passed': 64680},
    'fake': {'total': 1958472, 'passed': 375776}},
   'loose': {'det': {'total': 64972, 'passed': 64680},
    'fake': {'total': 1958472, 'passed': 375776}},
   'vloose': {'det': {'total': 64972, 'passed': 64680},
    'fake': {'total': 1958472, 'passed': 376406}}},
  {'tight': {'det': {'total': 26101, 'passed': 26007},
    'fake': {'total': 1951489, 'passed': 561188}},
   'medium': {'det': {'total': 26101, 'passed': 26017},
    'fake': {'total': 1951489, 'passed': 582851}},
   'loose': {'det': {'total': 26101, 'passed': 26017},
    'fake': {'total': 1951489, 'passed': 582851}},
   'vloose': {'det': {'total': 26101, 'passed': 26017},
    'fake': {'total': 1951489, 'passed': 582851}}},
  {'tight': {'det': {'total': 2047, 'passed': 1683},
    'fake': {'total': 1893649, 'passed': 112954}},
   'medium': {'det': {'total': 2047, 'passed': 1683},
    'fake': {'total': 1893649, 'passed': 112954}},
   'loose': {'det': {'total': 2047, 'passed': 1683},
    'fake': {'total': 1893649, 'passed': 112954}},
   'vloose': {'det': {'total': 2047, 'passed': 1688},
    'fake': {'total': 1893649, 'passed': 115985}}},
  {'tight': {'det': {'total': 16418, 'passed': 16118},
    'fake': {'total': 1961881, 'passed': 161982}},
   'medium': {'det': {'total': 16418, 'passed': 16136},
    'fake': {'total': 1961881, 'passed': 166163}},
   'loose': {'det': {'total': 16418, 'passed': 16138},
    'fake': {'total': 1961881, 'passed': 167203}},
   'vloose': {'det': {'total': 16418, 'passed': 16158},
    'fake': {'total': 1961881, 'passed': 170857}}},
  {'tight': {'det': {'total': 1408, 'passed': 1400},
    'fake': {'total': 672130, 'passed': 55292}},
   'medium': {'det': {'total': 1408, 'passed': 1400},
    'fake': {'total': 672130, 'passed': 55292}},
   'loose': {'det': {'total': 1408, 'passed': 1400},
    'fake': {'total': 672130, 'passed': 55292}},
   'vloose': {'det': {'total': 1408, 'passed': 1400},
    'fake': {'total': 672130, 'passed': 55292}}}],
 [{'tight': {'det': {'total': 387922, 'passed': 385620},
    'fake': {'total': 1960648, 'passed': 101260}},
   'medium': {'det': {'total': 387922, 'passed': 386540},
    'fake': {'total': 1960648, 'passed': 141013}},
   'loose': {'det': {'total': 387922, 'passed': 386520},
    'fake': {'total': 1960648, 'passed': 139522}},
   'vloose': {'det': {'total': 387922, 'passed': 387006},
    'fake': {'total': 1960648, 'passed': 220870}}},
  {'tight': {'det': {'total': 245647, 'passed': 244196},
    'fake': {'total': 1952533, 'passed': 157707}},
   'medium': {'det': {'total': 245647, 'passed': 244746},
    'fake': {'total': 1952533, 'passed': 206594}},
   'loose': {'det': {'total': 245647, 'passed': 244598},
    'fake': {'total': 1952533, 'passed': 188985}},
   'vloose': {'det': {'total': 245647, 'passed': 244944},
    'fake': {'total': 1952533, 'passed': 257690}}},
  {'tight': {'det': {'total': 82801, 'passed': 81351},
    'fake': {'total': 897621, 'passed': 97624}},
   'medium': {'det': {'total': 82801, 'passed': 81588},
    'fake': {'total': 897621, 'passed': 106633}},
   'loose': {'det': {'total': 82801, 'passed': 81842},
    'fake': {'total': 897621, 'passed': 118501}},
   'vloose': {'det': {'total': 82801, 'passed': 82228},
    'fake': {'total': 897621, 'passed': 156676}}},
  {'tight': {'det': {'total': 350188, 'passed': 347056},
    'fake': {'total': 1959057, 'passed': 119122}},
   'medium': {'det': {'total': 350188, 'passed': 348204},
    'fake': {'total': 1959057, 'passed': 142708}},
   'loose': {'det': {'total': 350188, 'passed': 347659},
    'fake': {'total': 1959057, 'passed': 128892}},
   'vloose': {'det': {'total': 350188, 'passed': 348396},
    'fake': {'total': 1959057, 'passed': 149851}}},
  {'tight': {'det': {'total': 33180, 'passed': 32926},
    'fake': {'total': 356013, 'passed': 33576}},
   'medium': {'det': {'total': 33180, 'passed': 33060},
    'fake': {'total': 356013, 'passed': 41516}},
   'loose': {'det': {'total': 33180, 'passed': 33030},
    'fake': {'total': 356013, 'passed': 38960}},
   'vloose': {'det': {'total': 33180, 'passed': 33098},
    'fake': {'total': 356013, 'passed': 47096}}}],
 [{'tight': {'det': {'total': 1659344, 'passed': 1651574},
    'fake': {'total': 1967693, 'passed': 55791}},
   'medium': {'det': {'total': 1659344, 'passed': 1655269},
    'fake': {'total': 1967693, 'passed': 73951}},
   'loose': {'det': {'total': 1659344, 'passed': 1655797},
    'fake': {'total': 1967693, 'passed': 79337}},
   'vloose': {'det': {'total': 1659344, 'passed': 1657259},
    'fake': {'total': 1967693, 'passed': 105537}}},
  {'tight': {'det': {'total': 1561786, 'passed': 1554814},
    'fake': {'total': 1960211, 'passed': 92541}},
   'medium': {'det': {'total': 1561786, 'passed': 1557571},
    'fake': {'total': 1960211, 'passed': 114242}},
   'loose': {'det': {'total': 1561786, 'passed': 1557742},
    'fake': {'total': 1960211, 'passed': 116200}},
   'vloose': {'det': {'total': 1561786, 'passed': 1559413},
    'fake': {'total': 1960211, 'passed': 150431}}},
  {'tight': {'det': {'total': 478121, 'passed': 463981},
    'fake': {'total': 575312, 'passed': 33832}},
   'medium': {'det': {'total': 478121, 'passed': 469602},
    'fake': {'total': 575312, 'passed': 43076}},
   'loose': {'det': {'total': 478121, 'passed': 470264},
    'fake': {'total': 575312, 'passed': 44691}},
   'vloose': {'det': {'total': 478121, 'passed': 472831},
    'fake': {'total': 575312, 'passed': 52902}}},
  {'tight': {'det': {'total': 1634658, 'passed': 1622043},
    'fake': {'total': 1965346, 'passed': 79683}},
   'medium': {'det': {'total': 1634658, 'passed': 1627008},
    'fake': {'total': 1965346, 'passed': 94710}},
   'loose': {'det': {'total': 1634658, 'passed': 1627051},
    'fake': {'total': 1965346, 'passed': 94925}},
   'vloose': {'det': {'total': 1634658, 'passed': 1629558},
    'fake': {'total': 1965346, 'passed': 110158}}},
  {'tight': {'det': {'total': 159854, 'passed': 158544},
    'fake': {'total': 259814, 'passed': 16456}},
   'medium': {'det': {'total': 159854, 'passed': 159066},
    'fake': {'total': 259814, 'passed': 19143}},
   'loose': {'det': {'total': 159854, 'passed': 158915},
    'fake': {'total': 259814, 'passed': 18148}},
   'vloose': {'det': {'total': 159854, 'passed': 159271},
    'fake': {'total': 259814, 'passed': 20952}}}],
 [{'tight': {'det': {'total': 1767690, 'passed': 1761691},
    'fake': {'total': 820051, 'passed': 14899}},
   'medium': {'det': {'total': 1767690, 'passed': 1764936},
    'fake': {'total': 820051, 'passed': 19815}},
   'loose': {'det': {'total': 1767690, 'passed': 1765520},
    'fake': {'total': 820051, 'passed': 21586}},
   'vloose': {'det': {'total': 1767690, 'passed': 1766515},
    'fake': {'total': 820051, 'passed': 27165}}},
  {'tight': {'det': {'total': 1752452, 'passed': 1747980},
    'fake': {'total': 626792, 'passed': 19896}},
   'medium': {'det': {'total': 1752452, 'passed': 1750000},
    'fake': {'total': 626792, 'passed': 24637}},
   'loose': {'det': {'total': 1752452, 'passed': 1750290},
    'fake': {'total': 626792, 'passed': 25671}},
   'vloose': {'det': {'total': 1752452, 'passed': 1751162},
    'fake': {'total': 626792, 'passed': 31338}}},
  {'tight': {'det': {'total': 1151059, 'passed': 1135328},
    'fake': {'total': 165113, 'passed': 8776}},
   'medium': {'det': {'total': 1151059, 'passed': 1139011},
    'fake': {'total': 165113, 'passed': 9867}},
   'loose': {'det': {'total': 1151059, 'passed': 1141760},
    'fake': {'total': 165113, 'passed': 10991}},
   'vloose': {'det': {'total': 1151059, 'passed': 1145858},
    'fake': {'total': 165113, 'passed': 13908}}},
  {'tight': {'det': {'total': 1685978, 'passed': 1676835},
    'fake': {'total': 752168, 'passed': 22005}},
   'medium': {'det': {'total': 1685978, 'passed': 1680983},
    'fake': {'total': 752168, 'passed': 26555}},
   'loose': {'det': {'total': 1685978, 'passed': 1681532},
    'fake': {'total': 752168, 'passed': 27518}},
   'vloose': {'det': {'total': 1685978, 'passed': 1683226},
    'fake': {'total': 752168, 'passed': 31806}}},
  {'tight': {'det': {'total': 340631, 'passed': 338258},
    'fake': {'total': 69973, 'passed': 2723}},
   'medium': {'det': {'total': 340631, 'passed': 338872},
    'fake': {'total': 69973, 'passed': 2961}},
   'loose': {'det': {'total': 340631, 'passed': 338829},
    'fake': {'total': 69973, 'passed': 2929}},
   'vloose': {'det': {'total': 340631, 'passed': 339535},
    'fake': {'total': 69973, 'passed': 3349}}}],
 [{'tight': {'det': {'total': 1810818, 'passed': 1806296},
    'fake': {'total': 306642, 'passed': 3872}},
   'medium': {'det': {'total': 1810818, 'passed': 1808763},
    'fake': {'total': 306642, 'passed': 5106}},
   'loose': {'det': {'total': 1810818, 'passed': 1809562},
    'fake': {'total': 306642, 'passed': 6091}},
   'vloose': {'det': {'total': 1810818, 'passed': 1810118},
    'fake': {'total': 306642, 'passed': 7605}}},
  {'tight': {'det': {'total': 1820279, 'passed': 1817026},
    'fake': {'total': 235538, 'passed': 5391}},
   'medium': {'det': {'total': 1820279, 'passed': 1818617},
    'fake': {'total': 235538, 'passed': 6662}},
   'loose': {'det': {'total': 1820279, 'passed': 1818935},
    'fake': {'total': 235538, 'passed': 7111}},
   'vloose': {'det': {'total': 1820279, 'passed': 1819396},
    'fake': {'total': 235538, 'passed': 8317}}},
  {'tight': {'det': {'total': 992666, 'passed': 980941},
    'fake': {'total': 63156, 'passed': 2716}},
   'medium': {'det': {'total': 992666, 'passed': 986031},
    'fake': {'total': 63156, 'passed': 3465}},
   'loose': {'det': {'total': 992666, 'passed': 986631},
    'fake': {'total': 63156, 'passed': 3607}},
   'vloose': {'det': {'total': 992666, 'passed': 988885},
    'fake': {'total': 63156, 'passed': 4375}}},
  {'tight': {'det': {'total': 1773587, 'passed': 1764013},
    'fake': {'total': 277412, 'passed': 5810}},
   'medium': {'det': {'total': 1773587, 'passed': 1767768},
    'fake': {'total': 277412, 'passed': 6695}},
   'loose': {'det': {'total': 1773587, 'passed': 1769299},
    'fake': {'total': 277412, 'passed': 7345}},
   'vloose': {'det': {'total': 1773587, 'passed': 1764493},
    'fake': {'total': 277412, 'passed': 5886}}},
  {'tight': {'det': {'total': 371729, 'passed': 369498},
    'fake': {'total': 25517, 'passed': 768}},
   'medium': {'det': {'total': 371729, 'passed': 369655},
    'fake': {'total': 25517, 'passed': 773}},
   'loose': {'det': {'total': 371729, 'passed': 370185},
    'fake': {'total': 25517, 'passed': 840}},
   'vloose': {'det': {'total': 371729, 'passed': 370278},
    'fake': {'total': 25517, 'passed': 849}}}],
 [{'tight': {'det': {'total': 1862230, 'passed': 1859444},
    'fake': {'total': 306686, 'passed': 3575}},
   'medium': {'det': {'total': 1862230, 'passed': 1860705},
    'fake': {'total': 306686, 'passed': 4620}},
   'loose': {'det': {'total': 1862230, 'passed': 1861184},
    'fake': {'total': 306686, 'passed': 5465}},
   'vloose': {'det': {'total': 1862230, 'passed': 1861660},
    'fake': {'total': 306686, 'passed': 7478}}},
  {'tight': {'det': {'total': 1885352, 'passed': 1882238},
    'fake': {'total': 240644, 'passed': 4398}},
   'medium': {'det': {'total': 1885352, 'passed': 1883655},
    'fake': {'total': 240644, 'passed': 5390}},
   'loose': {'det': {'total': 1885352, 'passed': 1883944},
    'fake': {'total': 240644, 'passed': 5785}},
   'vloose': {'det': {'total': 1885352, 'passed': 1884436},
    'fake': {'total': 240644, 'passed': 6884}}},
  {'tight': {'det': {'total': 384772, 'passed': 383093},
    'fake': {'total': 65781, 'passed': 3833}},
   'medium': {'det': {'total': 384772, 'passed': 382628},
    'fake': {'total': 65781, 'passed': 3494}},
   'loose': {'det': {'total': 384772, 'passed': 382947},
    'fake': {'total': 65781, 'passed': 3710}},
   'vloose': {'det': {'total': 384772, 'passed': 383550},
    'fake': {'total': 65781, 'passed': 4430}}},
  {'tight': {'det': {'total': 1619765, 'passed': 1613557},
    'fake': {'total': 267053, 'passed': 5333}},
   'medium': {'det': {'total': 1619765, 'passed': 1616369},
    'fake': {'total': 267053, 'passed': 6503}},
   'loose': {'det': {'total': 1619765, 'passed': 1617059},
    'fake': {'total': 267053, 'passed': 6964}},
   'vloose': {'det': {'total': 1619765, 'passed': 1618104},
    'fake': {'total': 267053, 'passed': 8035}}},
  {'tight': {'det': {'total': 120000, 'passed': 119662},
    'fake': {'total': 22441, 'passed': 753}},
   'medium': {'det': {'total': 120000, 'passed': 119786},
    'fake': {'total': 22441, 'passed': 835}},
   'loose': {'det': {'total': 120000, 'passed': 119815},
    'fake': {'total': 22441, 'passed': 863}},
   'vloose': {'det': {'total': 120000, 'passed': 119870},
    'fake': {'total': 22441, 'passed': 979}}}]]

In [37]:
et_bins = [
    '3000',
    '7000',
    '10000',
    '15000',
    '20000',
    '30000',
    '40000',
    '50000',
    'inf']
eta_bins = [
    '0.0',
    '0.8',
    '1.37',
    '1.54',
    '2.37',
    '2.5'
]

In [38]:
ref_data = defaultdict(list)
iterations = 0
for iet_bin, et_refs in enumerate(ref):
    et_bin_lower = et_bins[iet_bin]
    et_bin_upper = et_bins[iet_bin + 1]
    for ieta_bin, et_eta_refs in enumerate(et_refs):
        eta_bin_lower = eta_bins[ieta_bin]
        eta_bin_upper = eta_bins[ieta_bin + 1]
        for criteria, criteria_ref in et_eta_refs.items():
            for sample_type, sample_ref in criteria_ref.items():
                for total_or_passed, value in sample_ref.items():
                    print(f'{iterations} - ET Bin: {et_bin_lower}, {et_bin_upper}, ETA Bin: {eta_bin_lower}, {eta_bin_upper}, Criteria: {criteria}, Sample Type: {sample_type}, Total/Passed: {total_or_passed}, Value: {value}')
                    ref_data['et_bin_lower'].append(et_bin_lower)
                    ref_data['et_bin_upper'].append(et_bin_upper)
                    ref_data['eta_bin_lower'].append(eta_bin_lower)
                    ref_data['eta_bin_upper'].append(eta_bin_upper)
                    ref_data['criteria'].append(criteria)
                    ref_data['sample_type'].append(sample_type)
                    ref_data['total_or_passed'].append(total_or_passed)
                    ref_data['value'].append(value)
                    iterations += 1
ref_data = pd.DataFrame(ref_data)
ref_data

0 - ET Bin: 3000, 7000, ETA Bin: 0.0, 0.8, Criteria: tight, Sample Type: det, Total/Passed: total, Value: 232913
1 - ET Bin: 3000, 7000, ETA Bin: 0.0, 0.8, Criteria: tight, Sample Type: det, Total/Passed: passed, Value: 232060
2 - ET Bin: 3000, 7000, ETA Bin: 0.0, 0.8, Criteria: tight, Sample Type: fake, Total/Passed: total, Value: 1946524
3 - ET Bin: 3000, 7000, ETA Bin: 0.0, 0.8, Criteria: tight, Sample Type: fake, Total/Passed: passed, Value: 435731
4 - ET Bin: 3000, 7000, ETA Bin: 0.0, 0.8, Criteria: medium, Sample Type: det, Total/Passed: total, Value: 232913
5 - ET Bin: 3000, 7000, ETA Bin: 0.0, 0.8, Criteria: medium, Sample Type: det, Total/Passed: passed, Value: 232106
6 - ET Bin: 3000, 7000, ETA Bin: 0.0, 0.8, Criteria: medium, Sample Type: fake, Total/Passed: total, Value: 1946524
7 - ET Bin: 3000, 7000, ETA Bin: 0.0, 0.8, Criteria: medium, Sample Type: fake, Total/Passed: passed, Value: 449170
8 - ET Bin: 3000, 7000, ETA Bin: 0.0, 0.8, Criteria: loose, Sample Type: det, Total/Passed: total, Value: 232913
9 - ET Bin: 3000, 7000, ETA Bin: 0.0, 0.8, Criteria: loose, Sample Type: det, Total/Passed: passed, Value: 232102
10 - ET Bin: 3000, 7000, ETA Bin: 0.0, 0.8, Criteria: loose, Sample Type: fake, Total/Passed: total, Value: 1946524
11 - ET Bin: 3000, 7000, ETA Bin: 0.0, 0.8, Criteria: loose, Sample Type: fake, Total/Passed: passed, Value: 448182
12 - ET Bin: 3000, 7000, ETA Bin: 0.0, 0.8, Criteria: vloose, Sample Type: det, Total/Passed: total, Value: 232913
13 - ET Bin: 3000, 7000, ETA Bin: 0.0, 0.8, Criteria: vloose, Sample Type: det, Total/Passed: passed, Value: 232150
14 - ET Bin: 3000, 7000, ETA Bin: 0.0, 0.8, Criteria: vloose, Sample Type: fake, Total/Passed: total, Value: 1946524
15 - ET Bin: 3000, 7000, ETA Bin: 0.0, 0.8, Criteria: vloose, Sample Type: fake, Total/Passed: passed, Value: 464211
16 - ET Bin: 3000, 7000, ETA Bin: 0.8, 1.37, Criteria: tight, Sample Type: det, Total/Passed: total, Value: 73327
17 - ET Bin: 3000, 7000, ETA Bin: 0.8, 1.37, Criteria: tight, Sample Type: det, Total/Passed: passed, Value: 72911
18 - ET Bin: 3000, 7000, ETA Bin: 0.8, 1.37, Criteria: tight, Sample Type: fake, Total/Passed: total, Value: 1912796
19 - ET Bin: 3000, 7000, ETA Bin: 0.8, 1.37, Criteria: tight, Sample Type: fake, Total/Passed: passed, Value: 464002
20 - ET Bin: 3000, 7000, ETA Bin: 0.8, 1.37, Criteria: medium, Sample Type: det, Total/Passed: total, Value: 73327
21 - ET Bin: 3000, 7000, ETA Bin: 0.8, 1.37, Criteria: medium, Sample Type: det, Total/Passed: passed, Value: 72926
22 - ET Bin: 3000, 7000, ETA Bin: 0.8, 1.37, Criteria: medium, Sample Type: fake, Total/Passed: total, Value: 1912796
23 - ET Bin: 3000, 7000, ETA Bin: 0.8, 1.37, Criteria: medium, Sample Type: fake, Total/Passed: passed, Value: 474462
24 - ET Bin: 3000, 7000, ETA Bin: 0.8, 1.37, Criteria: loose, Sample Type: det, Total/Passed: total, Value: 73327
25 - ET Bin: 3000, 7000, ETA Bin: 0.8, 1.37, Criteria: loose, Sample Type: det, Total/Passed: passed, Value: 72952
26 - ET Bin: 3000, 7000, ETA Bin: 0.8, 1.37, Criteria: loose, Sample Type: fake, Total/Passed: total, Value: 1912796
27 - ET Bin: 3000, 7000, ETA Bin: 0.8, 1.37, Criteria: loose, Sample Type: fake, Total/Passed: passed, Value: 494841
28 - ET Bin: 3000, 7000, ETA Bin: 0.8, 1.37, Criteria: vloose, Sample Type: det, Total/Passed: total, Value: 73327
29 - ET Bin: 3000, 7000, ETA Bin: 0.8, 1.37, Criteria: vloose, Sample Type: det, Total/Passed: passed, Value: 72961
30 - ET Bin: 3000, 7000, ETA Bin: 0.8, 1.37, Criteria: vloose, Sample Type: fake, Total/Passed: total, Value: 1912796
31 - ET Bin: 3000, 7000, ETA Bin: 0.8, 1.37, Criteria: vloose, Sample Type: fake, Total/Passed: passed, Value: 504975
32 - ET Bin: 3000, 7000, ETA Bin: 1.37, 1.54, Criteria: tight, Sample Type: det, Total/Passed: total, Value: 3205
33 - ET Bin: 3000, 7000, ETA Bin: 1.37, 1.54, Criteria: tight, Sample Type: det, Total/Passed: passed, Value: 3010
34 - ET Bin: 3000, 7000, ETA Bin: 1.37, 1.54, Criteria: tight, Sample Type: fake, Total/Passed: total, Value: 936912
35 - ET Bin: 3000, 7000, ETA Bin: 1.37, 1.54, Criteria: tight, Sample Type: fake, Total/Passed: passed, Value: 131386
36 - ET Bin: 3000, 7000, ETA Bin: 1.37, 1.54, Criteria: medium, Sample Type: det, Total/Passed: total, Value: 3205
37 - ET Bin: 3000, 7000, ETA Bin: 1.37, 1.54, Criteria: medium, Sample Type: det, Total/Passed: passed, Value: 3042
38 - ET Bin: 3000, 7000, ETA Bin: 1.37, 1.54, Criteria: medium, Sample Type: fake, Total/Passed: total, Value: 936912
39 - ET Bin: 3000, 7000, ETA Bin: 1.37, 1.54, Criteria: medium, Sample Type: fake, Total/Passed: passed, Value: 143329
40 - ET Bin: 3000, 7000, ETA Bin: 1.37, 1.54, Criteria: loose, Sample Type: det, Total/Passed: total, Value: 3205
41 - ET Bin: 3000, 7000, ETA Bin: 1.37, 1.54, Criteria: loose, Sample Type: det, Total/Passed: passed, Value: 3043
42 - ET Bin: 3000, 7000, ETA Bin: 1.37, 1.54, Criteria: loose, Sample Type: fake, Total/Passed: total, Value: 936912
43 - ET Bin: 3000, 7000, ETA Bin: 1.37, 1.54, Criteria: loose, Sample Type: fake, Total/Passed: passed, Value: 144110
44 - ET Bin: 3000, 7000, ETA Bin: 1.37, 1.54, Criteria: vloose, Sample Type: det, Total/Passed: total, Value: 3205
45 - ET Bin: 3000, 7000, ETA Bin: 1.37, 1.54, Criteria: vloose, Sample Type: det, Total/Passed: passed, Value: 3056
46 - ET Bin: 3000, 7000, ETA Bin: 1.37, 1.54, Criteria: vloose, Sample Type: fake, Total/Passed: total, Value: 936912
47 - ET Bin: 3000, 7000, ETA Bin: 1.37, 1.54, Criteria: vloose, Sample Type: fake, Total/Passed: passed, Value: 157041
48 - ET Bin: 3000, 7000, ETA Bin: 1.54, 2.37, Criteria: tight, Sample Type: det, Total/Passed: total, Value: 54069
49 - ET Bin: 3000, 7000, ETA Bin: 1.54, 2.37, Criteria: tight, Sample Type: det, Total/Passed: passed, Value: 52272
50 - ET Bin: 3000, 7000, ETA Bin: 1.54, 2.37, Criteria: tight, Sample Type: fake, Total/Passed: total, Value: 1927127
51 - ET Bin: 3000, 7000, ETA Bin: 1.54, 2.37, Criteria: tight, Sample Type: fake, Total/Passed: passed, Value: 207715
52 - ET Bin: 3000, 7000, ETA Bin: 1.54, 2.37, Criteria: medium, Sample Type: det, Total/Passed: total, Value: 54069
53 - ET Bin: 3000, 7000, ETA Bin: 1.54, 2.37, Criteria: medium, Sample Type: det, Total/Passed: passed, Value: 52467
54 - ET Bin: 3000, 7000, ETA Bin: 1.54, 2.37, Criteria: medium, Sample Type: fake, Total/Passed: total, Value: 1927127
55 - ET Bin: 3000, 7000, ETA Bin: 1.54, 2.37, Criteria: medium, Sample Type: fake, Total/Passed: passed, Value: 218300
56 - ET Bin: 3000, 7000, ETA Bin: 1.54, 2.37, Criteria: loose, Sample Type: det, Total/Passed: total, Value: 54069
57 - ET Bin: 3000, 7000, ETA Bin: 1.54, 2.37, Criteria: loose, Sample Type: det, Total/Passed: passed, Value: 52535
58 - ET Bin: 3000, 7000, ETA Bin: 1.54, 2.37, Criteria: loose, Sample Type: fake, Total/Passed: total, Value: 1927127
59 - ET Bin: 3000, 7000, ETA Bin: 1.54, 2.37, Criteria: loose, Sample Type: fake, Total/Passed: passed, Value: 223883
60 - ET Bin: 3000, 7000, ETA Bin: 1.54, 2.37, Criteria: vloose, Sample Type: det, Total/Passed: total, Value: 54069
61 - ET Bin: 3000, 7000, ETA Bin: 1.54, 2.37, Criteria: vloose, Sample Type: det, Total/Passed: passed, Value: 52593
62 - ET Bin: 3000, 7000, ETA Bin: 1.54, 2.37, Criteria: vloose, Sample Type: fake, Total/Passed: total, Value: 1927127
63 - ET Bin: 3000, 7000, ETA Bin: 1.54, 2.37, Criteria: vloose, Sample Type: fake, Total/Passed: passed, Value: 226966
64 - ET Bin: 3000, 7000, ETA Bin: 2.37, 2.5, Criteria: tight, Sample Type: det, Total/Passed: total, Value: 3694
65 - ET Bin: 3000, 7000, ETA Bin: 2.37, 2.5, Criteria: tight, Sample Type: det, Total/Passed: passed, Value: 3625
66 - ET Bin: 3000, 7000, ETA Bin: 2.37, 2.5, Criteria: tight, Sample Type: fake, Total/Passed: total, Value: 530772
67 - ET Bin: 3000, 7000, ETA Bin: 2.37, 2.5, Criteria: tight, Sample Type: fake, Total/Passed: passed, Value: 65917
68 - ET Bin: 3000, 7000, ETA Bin: 2.37, 2.5, Criteria: medium, Sample Type: det, Total/Passed: total, Value: 3694
69 - ET Bin: 3000, 7000, ETA Bin: 2.37, 2.5, Criteria: medium, Sample Type: det, Total/Passed: passed, Value: 3631
70 - ET Bin: 3000, 7000, ETA Bin: 2.37, 2.5, Criteria: medium, Sample Type: fake, Total/Passed: total, Value: 530772
71 - ET Bin: 3000, 7000, ETA Bin: 2.37, 2.5, Criteria: medium, Sample Type: fake, Total/Passed: passed, Value: 68158
72 - ET Bin: 3000, 7000, ETA Bin: 2.37, 2.5, Criteria: loose, Sample Type: det, Total/Passed: total, Value: 3694
73 - ET Bin: 3000, 7000, ETA Bin: 2.37, 2.5, Criteria: loose, Sample Type: det, Total/Passed: passed, Value: 3632
74 - ET Bin: 3000, 7000, ETA Bin: 2.37, 2.5, Criteria: loose, Sample Type: fake, Total/Passed: total, Value: 530772
75 - ET Bin: 3000, 7000, ETA Bin: 2.37, 2.5, Criteria: loose, Sample Type: fake, Total/Passed: passed, Value: 68653
76 - ET Bin: 3000, 7000, ETA Bin: 2.37, 2.5, Criteria: vloose, Sample Type: det, Total/Passed: total, Value: 3694
77 - ET Bin: 3000, 7000, ETA Bin: 2.37, 2.5, Criteria: vloose, Sample Type: det, Total/Passed: passed, Value: 3632
78 - ET Bin: 3000, 7000, ETA Bin: 2.37, 2.5, Criteria: vloose, Sample Type: fake, Total/Passed: total, Value: 530772
79 - ET Bin: 3000, 7000, ETA Bin: 2.37, 2.5, Criteria: vloose, Sample Type: fake, Total/Passed: passed, Value: 68687
80 - ET Bin: 7000, 10000, ETA Bin: 0.0, 0.8, Criteria: tight, Sample Type: det, Total/Passed: total, Value: 132921
81 - ET Bin: 7000, 10000, ETA Bin: 0.0, 0.8, Criteria: tight, Sample Type: det, Total/Passed: passed, Value: 132518
82 - ET Bin: 7000, 10000, ETA Bin: 0.0, 0.8, Criteria: tight, Sample Type: fake, Total/Passed: total, Value: 1963194
83 - ET Bin: 7000, 10000, ETA Bin: 0.0, 0.8, Criteria: tight, Sample Type: fake, Total/Passed: passed, Value: 530493
84 - ET Bin: 7000, 10000, ETA Bin: 0.0, 0.8, Criteria: medium, Sample Type: det, Total/Passed: total, Value: 132921
85 - ET Bin: 7000, 10000, ETA Bin: 0.0, 0.8, Criteria: medium, Sample Type: det, Total/Passed: passed, Value: 132526
86 - ET Bin: 7000, 10000, ETA Bin: 0.0, 0.8, Criteria: medium, Sample Type: fake, Total/Passed: total, Value: 1963194
87 - ET Bin: 7000, 10000, ETA Bin: 0.0, 0.8, Criteria: medium, Sample Type: fake, Total/Passed: passed, Value: 547578
88 - ET Bin: 7000, 10000, ETA Bin: 0.0, 0.8, Criteria: loose, Sample Type: det, Total/Passed: total, Value: 132921
89 - ET Bin: 7000, 10000, ETA Bin: 0.0, 0.8, Criteria: loose, Sample Type: det, Total/Passed: passed, Value: 132530
90 - ET Bin: 7000, 10000, ETA Bin: 0.0, 0.8, Criteria: loose, Sample Type: fake, Total/Passed: total, Value: 1963194
91 - ET Bin: 7000, 10000, ETA Bin: 0.0, 0.8, Criteria: loose, Sample Type: fake, Total/Passed: passed, Value: 556101
92 - ET Bin: 7000, 10000, ETA Bin: 0.0, 0.8, Criteria: vloose, Sample Type: det, Total/Passed: total, Value: 132921
93 - ET Bin: 7000, 10000, ETA Bin: 0.0, 0.8, Criteria: vloose, Sample Type: det, Total/Passed: passed, Value: 132530
94 - ET Bin: 7000, 10000, ETA Bin: 0.0, 0.8, Criteria: vloose, Sample Type: fake, Total/Passed: total, Value: 1963194
95 - ET Bin: 7000, 10000, ETA Bin: 0.0, 0.8, Criteria: vloose, Sample Type: fake, Total/Passed: passed, Value: 557466
96 - ET Bin: 7000, 10000, ETA Bin: 0.8, 1.37, Criteria: tight, Sample Type: det, Total/Passed: total, Value: 51488
97 - ET Bin: 7000, 10000, ETA Bin: 0.8, 1.37, Criteria: tight, Sample Type: det, Total/Passed: passed, Value: 51243
98 - ET Bin: 7000, 10000, ETA Bin: 0.8, 1.37, Criteria: tight, Sample Type: fake, Total/Passed: total, Value: 1939077
99 - ET Bin: 7000, 10000, ETA Bin: 0.8, 1.37, Criteria: tight, Sample Type: fake, Total/Passed: passed, Value: 456128
100 - ET Bin: 7000, 10000, ETA Bin: 0.8, 1.37, Criteria: medium, Sample Type: det, Total/Passed: total, Value: 51488
101 - ET Bin: 7000, 10000, ETA Bin: 0.8, 1.37, Criteria: medium, Sample Type: det, Total/Passed: passed, Value: 51243
102 - ET Bin: 7000, 10000, ETA Bin: 0.8, 1.37, Criteria: medium, Sample Type: fake, Total/Passed: total, Value: 1939077
103 - ET Bin: 7000, 10000, ETA Bin: 0.8, 1.37, Criteria: medium, Sample Type: fake, Total/Passed: passed, Value: 456128
104 - ET Bin: 7000, 10000, ETA Bin: 0.8, 1.37, Criteria: loose, Sample Type: det, Total/Passed: total, Value: 51488
105 - ET Bin: 7000, 10000, ETA Bin: 0.8, 1.37, Criteria: loose, Sample Type: det, Total/Passed: passed, Value: 51240
106 - ET Bin: 7000, 10000, ETA Bin: 0.8, 1.37, Criteria: loose, Sample Type: fake, Total/Passed: total, Value: 1939077
107 - ET Bin: 7000, 10000, ETA Bin: 0.8, 1.37, Criteria: loose, Sample Type: fake, Total/Passed: passed, Value: 448309
108 - ET Bin: 7000, 10000, ETA Bin: 0.8, 1.37, Criteria: vloose, Sample Type: det, Total/Passed: total, Value: 51488
109 - ET Bin: 7000, 10000, ETA Bin: 0.8, 1.37, Criteria: vloose, Sample Type: det, Total/Passed: passed, Value: 51250
110 - ET Bin: 7000, 10000, ETA Bin: 0.8, 1.37, Criteria: vloose, Sample Type: fake, Total/Passed: total, Value: 1939077
111 - ET Bin: 7000, 10000, ETA Bin: 0.8, 1.37, Criteria: vloose, Sample Type: fake, Total/Passed: passed, Value: 463446
112 - ET Bin: 7000, 10000, ETA Bin: 1.37, 1.54, Criteria: tight, Sample Type: det, Total/Passed: total, Value: 3039
113 - ET Bin: 7000, 10000, ETA Bin: 1.37, 1.54, Criteria: tight, Sample Type: det, Total/Passed: passed, Value: 2856
114 - ET Bin: 7000, 10000, ETA Bin: 1.37, 1.54, Criteria: tight, Sample Type: fake, Total/Passed: total, Value: 1492017
115 - ET Bin: 7000, 10000, ETA Bin: 1.37, 1.54, Criteria: tight, Sample Type: fake, Total/Passed: passed, Value: 164794
116 - ET Bin: 7000, 10000, ETA Bin: 1.37, 1.54, Criteria: medium, Sample Type: det, Total/Passed: total, Value: 3039
117 - ET Bin: 7000, 10000, ETA Bin: 1.37, 1.54, Criteria: medium, Sample Type: det, Total/Passed: passed, Value: 2856
118 - ET Bin: 7000, 10000, ETA Bin: 1.37, 1.54, Criteria: medium, Sample Type: fake, Total/Passed: total, Value: 1492017
119 - ET Bin: 7000, 10000, ETA Bin: 1.37, 1.54, Criteria: medium, Sample Type: fake, Total/Passed: passed, Value: 165295
120 - ET Bin: 7000, 10000, ETA Bin: 1.37, 1.54, Criteria: loose, Sample Type: det, Total/Passed: total, Value: 3039
121 - ET Bin: 7000, 10000, ETA Bin: 1.37, 1.54, Criteria: loose, Sample Type: det, Total/Passed: passed, Value: 2857
122 - ET Bin: 7000, 10000, ETA Bin: 1.37, 1.54, Criteria: loose, Sample Type: fake, Total/Passed: total, Value: 1492017
123 - ET Bin: 7000, 10000, ETA Bin: 1.37, 1.54, Criteria: loose, Sample Type: fake, Total/Passed: passed, Value: 165646
124 - ET Bin: 7000, 10000, ETA Bin: 1.37, 1.54, Criteria: vloose, Sample Type: det, Total/Passed: total, Value: 3039
125 - ET Bin: 7000, 10000, ETA Bin: 1.37, 1.54, Criteria: vloose, Sample Type: det, Total/Passed: passed, Value: 2864
126 - ET Bin: 7000, 10000, ETA Bin: 1.37, 1.54, Criteria: vloose, Sample Type: fake, Total/Passed: total, Value: 1492017
127 - ET Bin: 7000, 10000, ETA Bin: 1.37, 1.54, Criteria: vloose, Sample Type: fake, Total/Passed: passed, Value: 171130
128 - ET Bin: 7000, 10000, ETA Bin: 1.54, 2.37, Criteria: tight, Sample Type: det, Total/Passed: total, Value: 31538
129 - ET Bin: 7000, 10000, ETA Bin: 1.54, 2.37, Criteria: tight, Sample Type: det, Total/Passed: passed, Value: 30724
130 - ET Bin: 7000, 10000, ETA Bin: 1.54, 2.37, Criteria: tight, Sample Type: fake, Total/Passed: total, Value: 1956239
131 - ET Bin: 7000, 10000, ETA Bin: 1.54, 2.37, Criteria: tight, Sample Type: fake, Total/Passed: passed, Value: 147982
132 - ET Bin: 7000, 10000, ETA Bin: 1.54, 2.37, Criteria: medium, Sample Type: det, Total/Passed: total, Value: 31538
133 - ET Bin: 7000, 10000, ETA Bin: 1.54, 2.37, Criteria: medium, Sample Type: det, Total/Passed: passed, Value: 30807
134 - ET Bin: 7000, 10000, ETA Bin: 1.54, 2.37, Criteria: medium, Sample Type: fake, Total/Passed: total, Value: 1956239
135 - ET Bin: 7000, 10000, ETA Bin: 1.54, 2.37, Criteria: medium, Sample Type: fake, Total/Passed: passed, Value: 157614
136 - ET Bin: 7000, 10000, ETA Bin: 1.54, 2.37, Criteria: loose, Sample Type: det, Total/Passed: total, Value: 31538
137 - ET Bin: 7000, 10000, ETA Bin: 1.54, 2.37, Criteria: loose, Sample Type: det, Total/Passed: passed, Value: 30831
138 - ET Bin: 7000, 10000, ETA Bin: 1.54, 2.37, Criteria: loose, Sample Type: fake, Total/Passed: total, Value: 1956239
139 - ET Bin: 7000, 10000, ETA Bin: 1.54, 2.37, Criteria: loose, Sample Type: fake, Total/Passed: passed, Value: 159144
140 - ET Bin: 7000, 10000, ETA Bin: 1.54, 2.37, Criteria: vloose, Sample Type: det, Total/Passed: total, Value: 31538
141 - ET Bin: 7000, 10000, ETA Bin: 1.54, 2.37, Criteria: vloose, Sample Type: det, Total/Passed: passed, Value: 30863
142 - ET Bin: 7000, 10000, ETA Bin: 1.54, 2.37, Criteria: vloose, Sample Type: fake, Total/Passed: total, Value: 1956239
143 - ET Bin: 7000, 10000, ETA Bin: 1.54, 2.37, Criteria: vloose, Sample Type: fake, Total/Passed: passed, Value: 163497
144 - ET Bin: 7000, 10000, ETA Bin: 2.37, 2.5, Criteria: tight, Sample Type: det, Total/Passed: total, Value: 2541
145 - ET Bin: 7000, 10000, ETA Bin: 2.37, 2.5, Criteria: tight, Sample Type: det, Total/Passed: passed, Value: 2515
146 - ET Bin: 7000, 10000, ETA Bin: 2.37, 2.5, Criteria: tight, Sample Type: fake, Total/Passed: total, Value: 773678
147 - ET Bin: 7000, 10000, ETA Bin: 2.37, 2.5, Criteria: tight, Sample Type: fake, Total/Passed: passed, Value: 74926
148 - ET Bin: 7000, 10000, ETA Bin: 2.37, 2.5, Criteria: medium, Sample Type: det, Total/Passed: total, Value: 2541
149 - ET Bin: 7000, 10000, ETA Bin: 2.37, 2.5, Criteria: medium, Sample Type: det, Total/Passed: passed, Value: 2515
150 - ET Bin: 7000, 10000, ETA Bin: 2.37, 2.5, Criteria: medium, Sample Type: fake, Total/Passed: total, Value: 773678
151 - ET Bin: 7000, 10000, ETA Bin: 2.37, 2.5, Criteria: medium, Sample Type: fake, Total/Passed: passed, Value: 74987
152 - ET Bin: 7000, 10000, ETA Bin: 2.37, 2.5, Criteria: loose, Sample Type: det, Total/Passed: total, Value: 2541
153 - ET Bin: 7000, 10000, ETA Bin: 2.37, 2.5, Criteria: loose, Sample Type: det, Total/Passed: passed, Value: 2515
154 - ET Bin: 7000, 10000, ETA Bin: 2.37, 2.5, Criteria: loose, Sample Type: fake, Total/Passed: total, Value: 773678
155 - ET Bin: 7000, 10000, ETA Bin: 2.37, 2.5, Criteria: loose, Sample Type: fake, Total/Passed: passed, Value: 74987
156 - ET Bin: 7000, 10000, ETA Bin: 2.37, 2.5, Criteria: vloose, Sample Type: det, Total/Passed: total, Value: 2541
157 - ET Bin: 7000, 10000, ETA Bin: 2.37, 2.5, Criteria: vloose, Sample Type: det, Total/Passed: passed, Value: 2515
158 - ET Bin: 7000, 10000, ETA Bin: 2.37, 2.5, Criteria: vloose, Sample Type: fake, Total/Passed: total, Value: 773678
159 - ET Bin: 7000, 10000, ETA Bin: 2.37, 2.5, Criteria: vloose, Sample Type: fake, Total/Passed: passed, Value: 74987
160 - ET Bin: 10000, 15000, ETA Bin: 0.0, 0.8, Criteria: tight, Sample Type: det, Total/Passed: total, Value: 64972
161 - ET Bin: 10000, 15000, ETA Bin: 0.0, 0.8, Criteria: tight, Sample Type: det, Total/Passed: passed, Value: 64678
162 - ET Bin: 10000, 15000, ETA Bin: 0.0, 0.8, Criteria: tight, Sample Type: fake, Total/Passed: total, Value: 1958472
163 - ET Bin: 10000, 15000, ETA Bin: 0.0, 0.8, Criteria: tight, Sample Type: fake, Total/Passed: passed, Value: 374198
164 - ET Bin: 10000, 15000, ETA Bin: 0.0, 0.8, Criteria: medium, Sample Type: det, Total/Passed: total, Value: 64972
165 - ET Bin: 10000, 15000, ETA Bin: 0.0, 0.8, Criteria: medium, Sample Type: det, Total/Passed: passed, Value: 64680
166 - ET Bin: 10000, 15000, ETA Bin: 0.0, 0.8, Criteria: medium, Sample Type: fake, Total/Passed: total, Value: 1958472
167 - ET Bin: 10000, 15000, ETA Bin: 0.0, 0.8, Criteria: medium, Sample Type: fake, Total/Passed: passed, Value: 375776
168 - ET Bin: 10000, 15000, ETA Bin: 0.0, 0.8, Criteria: loose, Sample Type: det, Total/Passed: total, Value: 64972
169 - ET Bin: 10000, 15000, ETA Bin: 0.0, 0.8, Criteria: loose, Sample Type: det, Total/Passed: passed, Value: 64680

,et_bin_lower,et_bin_upper,eta_bin_lower,eta_bin_upper,criteria,sample_type,total_or_passed,value
0,3000,7000,0.0,0.8,tight,det,total,232913
1,3000,7000,0.0,0.8,tight,det,passed,232060
2,3000,7000,0.0,0.8,tight,fake,total,1946524
3,3000,7000,0.0,0.8,tight,fake,passed,435731
4,3000,7000,0.0,0.8,medium,det,total,232913
...,...,...,...,...,...,...,...,...
635,50000,inf,2.37,2.5,loose,fake,passed,863
636,50000,inf,2.37,2.5,vloose,det,total,120000
637,50000,inf,2.37,2.5,vloose,det,passed,119870
638,50000,inf,2.37,2.5,vloose,fake,total,22441
639,50000,inf,2.37,2.5,vloose,fake,passed,979

In [39]:
ref_data.dtypes

et_bin_lower         str
et_bin_upper         str
eta_bin_lower        str
eta_bin_upper        str
criteria             str
sample_type          str
total_or_passed      str
value              int64
dtype: object

In [40]:
ref_data = ref_data.convert_dtypes(dtype_backend='pyarrow')
ref_data['et_bin_lower'] = ref_data['et_bin_lower'].astype('float32[pyarrow]')
ref_data['et_bin_upper'] = ref_data['et_bin_upper'].astype('float32[pyarrow]')
ref_data['eta_bin_lower'] = ref_data['eta_bin_lower'].astype('float32[pyarrow]')
ref_data['eta_bin_upper'] = ref_data['eta_bin_upper'].astype('float32[pyarrow]')
ref_data['value'] = ref_data['value'].astype('uint64[pyarrow]')
ref_data.dtypes

et_bin_lower        float[pyarrow]
et_bin_upper        float[pyarrow]
eta_bin_lower       float[pyarrow]
eta_bin_upper       float[pyarrow]
criteria           string[pyarrow]
sample_type        string[pyarrow]
total_or_passed    string[pyarrow]
value              uint64[pyarrow]
dtype: object

In [41]:
expected_ref_data_schema = pa.DataFrameSchema({
    'et_bin_lower': pa.Column(
        'float32[pyarrow]',
        checks=[
            pa.Check.ge(0)
        ]
    ),
    'et_bin_upper': pa.Column(
        'float32[pyarrow]',
        checks=[
            pa.Check.ge(0)
        ]
    ),
    'eta_bin_lower': pa.Column(
        'float32[pyarrow]',
        checks=[
            pa.Check.ge(0)
        ]
    ),
    'eta_bin_upper': pa.Column(
        'float32[pyarrow]',
        checks=[
            pa.Check.ge(0)
        ]
    ),
    'criteria': pa.Column(
        pd.ArrowDtype(pyarrow.string()),
        checks=[
            pa.Check.isin(['tight', 'medium', 'loose', 'vloose'])
        ],
    ),
    'sample_type': pa.Column(
        pd.ArrowDtype(pyarrow.string()),
        checks=[
            pa.Check.isin(['det', 'fake'])
        ]
    ),
    'total_or_passed': pa.Column(
        pd.ArrowDtype(pyarrow.string()),
        checks=[
            pa.Check.isin(['total', 'passed'])
        ]
    ),
    'value': pa.Column(
        'uint64[pyarrow]',
        checks=[
            pa.Check.ge(0)
        ]
    )
})

In [42]:
ref_data = expected_ref_data_schema.validate(ref_data)
ref_data

,et_bin_lower,et_bin_upper,eta_bin_lower,eta_bin_upper,criteria,sample_type,total_or_passed,value
0,3000.0,7000.0,0.0,0.8,tight,det,total,232913
1,3000.0,7000.0,0.0,0.8,tight,det,passed,232060
2,3000.0,7000.0,0.0,0.8,tight,fake,total,1946524
3,3000.0,7000.0,0.0,0.8,tight,fake,passed,435731
4,3000.0,7000.0,0.0,0.8,medium,det,total,232913
...,...,...,...,...,...,...,...,...
635,50000.0,inf,2.37,2.5,loose,fake,passed,863
636,50000.0,inf,2.37,2.5,vloose,det,total,120000
637,50000.0,inf,2.37,2.5,vloose,det,passed,119870
638,50000.0,inf,2.37,2.5,vloose,fake,total,22441
639,50000.0,inf,2.37,2.5,vloose,fake,passed,979

In [44]:
ref_data.to_parquet(output_dir.parent / 'ref.parquet')